adds unlock feature as a button
Neufund/platform-frontend pull request #4551
Opened 2020-08-18 11:38 UTC by Moejoe90

2020-08-24 08:10 UTC, desfero commented on packages/web/app/modules/wallet-view/sagas.spec.ts
> +              } as any,
can we avoid `as any`? Maybe Partial<TAppState> or `DeepPartial<TAPPState>`?

2020-08-24 08:26 UTC, desfero requested changes
Small changes requested

2020-08-24 08:26 UTC, desfero commented on packages/web/app/modules/wallet-view/sagas.ts
> +        const { balanceData, totalBalanceEuro } = yield* call(populateBalanceData);
The problem we have now is that when `tx history` is updated then a new reference for `balanceData` is generated which in turn rerenders the UI not related to tx history. Not a big deal but seems like a code smell. I would say we need to move all of that to selectors to derive data only when there is really a change in sub modules.

2020-08-24 08:36 UTC, desfero commented on packages/web/app/components/wallet/utils.tsx
> +      dispatchAction: () => dispatch(actions.txTransactions.startUnlockEtherFunds()),
can we remove dispatch(actions.txTransactions.startUnlockEtherFunds()) as it should never happen here given it's always disabled, same on line `179`. Also would be good to add some kind of comment why `disabledIf` is always true

2020-08-24 09:09 UTC, Moejoe90 commented on packages/web/app/modules/wallet-view/sagas.spec.ts
> +              } as any,
but this is a test file. I could argue its better like this to make it clear this is not typed correctly

2020-08-25 13:44 UTC, desfero commented on packages/web/app/modules/wallet-view/sagas.spec.ts
> +              } as any,
the case if DeepPartial is that when you move part of states to for .e.g modules under the different name you get a clear error from tsc so you know what to fix. Also the same with any kind of renaming or type changes

2020-09-03 15:33 UTC, AlexeyTuboltsev commented on packages/web/app/components/wallet/BalanceList.tsx
> +        <Balance {...b} key={b.balanceId} />
unfortunately we can't ban numeric keys on lint level, but they definitely should be a red flag for reviewer

2020-09-03 15:37 UTC, AlexeyTuboltsev commented on packages/web/app/components/wallet/BalanceList.tsx
> +        <Balance {...b} key={b.balanceId} />
since all the data comes from sagas, there's no problem to generate normal string keys, even `math.random().toString()` would do if there's no sensible alternative to it

2020-09-04 11:04 UTC, desfero approved these changes

2020-09-04 20:35 UTC, desfero submitted a review, later dismissed

2020-09-07 13:10 UTC, glupiawymowka requested changes
- [ ] `Icbm` should've been fixed to capital letters as per design
![image](https://user-images.githubusercontent.com/18315589/92390955-2461f800-f11c-11ea-8a45-6b70d7774762.png)

2020-09-08 09:59 UTC, glupiawymowka approved these changes

2020-09-08 09:59 UTC, merged