Simple issuer voting self service
Neufund/platform-frontend pull request #4574
Opened 2020-09-14 12:57 UTC by arjunu

2020-09-14 15:07 UTC, arjunu commented on packages/design-system/src/components/inputs/Checkbox.module.scss
> +  margin-top: 3px;
because for multiline labels the checkbox should be aligned with the first line

2020-09-14 15:10 UTC, arjunu commented on packages/shared-modules/src/modules/auth/jwt/types.ts
> +  UPLOAD_ISSUER_IMMUTABLE_DOCUMENT = "upload-issuer-immutable-document",
to avoid conflict with the permission `upload-immutable-document`

2020-09-14 15:12 UTC, arjunu commented on packages/shared-utils/src/utils/enums/file.ts
> +export enum EMimeType {
moved here from web package

2020-09-14 15:15 UTC, arjunu commented on packages/web/app/components/shared/forms/fields/utils.tsx
> -export enum EMimeType {
moved to shared utils

2020-09-19 14:33 UTC, arjunu commented on packages/web/app/modules/tx/transactions/shareholder-resolution-vote/vote/sagas.ts
> +import { call, put, SagaGenerator, select } from "@neufund/sagas";
Moved file from `packages/web/app/modules/tx/transactions/shareholder-resolution-vote/sagas.ts`

2020-09-23 15:21 UTC, desfero requested changes
A couple of code comments and UI issues reported directly slack

2020-09-23 15:21 UTC, desfero commented on packages/web/intl/locales/en-en.json
> +  "shareholder-resolution-widget.text": "Create a new shareholder resolution you require your tokenholders to vote on.",
Sentence sound like a broken one. Was that taken from the ticket?

2020-09-23 15:21 UTC, desfero commented on packages/web/intl/locales/en-en.json
> +  "eto-dashboard.new-voting-resolution-modal.summary.description": "Please review the shareholder resolution before you publish it. Once published, voting will start immediately and I cannot cancel a
Not sure, but maybe `and you cannot cancel and/or`

2020-09-23 15:21 UTC, desfero commented on packages/web/app/test-e2e/issuer/governance/OffChainVotesUpload.spec.e2e.ts
> +    assertVotingSetup(withTallyFormData);
Would be good if we can reuse already existing proposal from `open_proposals.json` to reduce the time test needs to setup voting from scratch

2020-09-24 09:25 UTC, arjunu commented on packages/design-system/src/components/inputs/Checkbox.module.scss
> +  align-self: start;
done. I think I saw a warning from Chrome saying `start` is invalid. Didn't realise it was from checkbox.

2020-09-24 10:06 UTC, arjunu commented on packages/design-system/src/components/inputs/TextField.tsx
> +  smallWidth?: boolean;
done

2020-09-24 10:10 UTC, arjunu commented on packages/design-system/src/components/inputs/TextField.tsx
> +            {smallWidth && units && <span className={styles.units}>{units}</span>}
by default textfield is block width, so can't show units there

2020-09-24 10:46 UTC, arjunu commented on packages/shared-modules/src/modules/eto/lib/http/eto-api/EtoFileApi.ts
> +  public async uploadCompanyDocument(
Good idea, moved.

2020-09-24 11:22 UTC, arjunu commented on packages/web/app/components/governance/proposal/UploadVotingResultsModal.tsx
> +  show: boolean;
changed to `visible`.

2020-09-24 15:58 UTC, arjunu commented on packages/web/app/components/governance/proposal/UploadVotingResultsModal.tsx
> +  show: boolean;
Used field level validation and submit prop.

2020-09-24 15:59 UTC, arjunu commented on packages/web/app/components/governance/proposal/UploadVotingResultsModal.tsx
> +        onSubmit={() => {}}
done

2020-09-24 15:59 UTC, arjunu commented on packages/web/app/components/governance/proposal/UploadVotingResultsModal.tsx
> +                <div className={styles.totalError}>
added

2020-09-24 16:44 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionForm.tsx
> +      onSubmit={() => {}}
done

2020-09-24 16:50 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionForm.tsx
> +                <div className={styles.afterUploadMessage}>
changed to `p`

2020-09-24 16:51 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionForm.tsx
> +                props.uploadedDocument
done

2020-09-24 16:53 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionModal.module.scss
> +  font-family: $font-family-roboto;
removed

2020-09-24 16:55 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/ResolutionPublishSuccessModal.tsx
> +      <img src={successImage} alt="Success" />
removed

2020-09-24 16:57 UTC, arjunu commented on packages/web/app/components/settings/verify-email/AccountSetupVerifyEmailComponent.tsx
> +          <FormattedMessage id="form.button.CONTINUE" />
both cases are being used. I guess in the design the button has upper case test.
```
 "form.button.CONTINUE": "CONTINUE",
  "form.button.continue": "Continue",
```

2020-09-24 16:58 UTC, arjunu commented on packages/web/app/components/shared/MultiFileUpload.tsx
> +      <p className={styles.uploadTitle}>{uploadTitle || selectTitle(uploadType)}</p>
added

2020-09-24 17:01 UTC, arjunu commented on packages/web/app/components/shared/UploadedFiles.stories.tsx
> +  <UploadedFiles files={files} onDelete={action("onDeleteClick")} />
added

2020-09-24 17:06 UTC, arjunu commented on packages/web/app/modules/actions.ts
> +  shareholderResolutionsVotingSetup: shareholderResolutionsVotingSetupModuleApi.actions,
The reason I added them here was because `TActionPayload` uses the types from the actions. Now I did:
`type TActions = typeof actions & typeof moduleActions;`

2020-09-24 17:07 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-setup/reducer.ts
> +  showNewVotingResolutionModal: boolean;
changed

2020-09-24 17:12 UTC, arjunu commented on packages/web/intl/locales/en-en.json
> +  "shareholder-resolution-widget.text": "Create a new shareholder resolution you require your tokenholders to vote on.",
It sounds valid to me.

2020-09-24 17:12 UTC, arjunu commented on packages/web/intl/locales/en-en.json
> +  "shareholder-resolution-widget.title": "SHAREHOLDER RESOLUTIONS",
fixed

2020-09-24 17:16 UTC, arjunu commented on packages/web/intl/locales/en-en.json
> +  "eto-dashboard.new-voting-resolution-modal.summary.description": "Please review the shareholder resolution before you publish it. Once published, voting will start immediately and I cannot cancel a
fixed

2020-09-24 17:28 UTC, arjunu commented on packages/web/intl/locales/en-en.json
> +  "governance.proposal.voting.details.submit-by": "Please submit your final voting results by",
Here the problem was I need the date to be on a new line so I have to use break tags which means I need to use `FormattedHTMLMessage` and `FormattedDate` doesn't work inside `FormattedHTMLMessage`. The other alternative is to use `moment`'s format. Given we want to move away from it, I'll leave this like this?

2020-09-24 17:34 UTC, arjunu commented on packages/web/intl/locales/en-en.json
> +  "governance.proposal.voting.details.submit-by": "Please submit your final voting results by",
used `separator: <br />`

2020-09-24 17:42 UTC, arjunu commented on packages/web/intl/locales/en-en.json
> +  "eto-dashboard.voting-resolution-published-modal.description": "Your shareholder resolution was published. Please keep an eye on your email for confirmation and any necessary required actions.<br/>
updated

2020-09-24 17:46 UTC, arjunu commented on packages/web/app/test-e2e/issuer/governance/OffChainVotesUpload.spec.e2e.ts
> +    assertVotingSetup(withTallyFormData);
done

2020-09-24 17:52 UTC, arjunu commented on packages/web/app/modules/tx/transactions/shareholder-resolution-vote/setup/sagas.ts
> +  const votingPeriod = Number(votingResolution.votingDuration) * 24 * 60 * 60; // days to seconds
added

2020-09-24 17:52 UTC, arjunu commented on packages/web/app/modules/tx/transactions/shareholder-resolution-vote/setup/sagas.ts
> +    ? Number(votingResolution.submissionDeadline) * 24 * 60 * 60
added

2020-09-24 17:53 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-view/types.ts
> +export type TOffChainVotesFormData = {
oops, removed

2020-09-24 17:57 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-view/types.ts
> +  iUnderstand: Yup.boolean().required(),
thanks that's much better

2020-09-24 17:57 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-view/reducer.ts
> +  showUploadVotingResultsModal: boolean;
updated

2020-09-24 18:00 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-setup/document-upload/sagas.ts
> +): Generator<any, any, any> {
fixed

2020-09-25 08:47 UTC, arjunu commented on packages/web/app/components/governance/proposal/voting-details/ProposalVotingDetails.tsx
> +            <FormattedHTMLMessage
done

2020-09-25 08:58 UTC, arjunu commented on packages/web/app/components/governance/proposal/UploadVotingResultsModal.tsx
> +import { Button, Checkbox, EButtonLayout, Eur, TextField } from "@neufund/design-system";
added

2020-09-25 08:58 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionForm.tsx
> +            values.includeExternalVotes &&
moved to field level validation

2020-09-25 15:51 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionModal.module.scss
> +.summary {
moved

2020-09-25 16:03 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionModal.module.scss
> +.edit-button {
nice, used it.

2020-09-25 16:05 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/ResolutionPublishSuccessModal.module.scss
> +  color: $neu-dark-blue;
removed

2020-09-25 16:07 UTC, arjunu commented on packages/web/app/components/shared/UploadedFiles.module.scss
> +  & path {
updated

2020-09-25 16:09 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-setup/selectors.ts
> +import { TAppGlobalState } from "../../store";
changed

2020-09-25 16:10 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-setup/sagas.ts
> +  const tokensAsShareCapital = tokensToShareCapital(tokens, shareNominalValueUlps, tokensPerShare);
changed

2020-09-25 16:14 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-setup/sagas.ts
> +      convertFromUlps(shareCapital.toString()).toString(),
Updated

2020-09-25 16:48 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionForm.tsx
> +                    <img src={InfoIcon} alt="" className="mt-2" />
removed, yeah we could.

2020-09-28 14:37 UTC, arjunu commented on packages/design-system/src/components/inputs/TextField.tsx
> +            {smallWidth && units && <span className={styles.units}>{units}</span>}
used flex to show units

2020-09-28 17:22 UTC, arjunu commented on packages/web/app/components/governance/proposal/UploadVotingResultsModal.tsx
> +import { ModalFooter } from "reactstrap";
noted

2020-09-28 17:22 UTC, arjunu commented on packages/web/app/components/governance/proposal/UploadVotingResultsModal.module.scss
> +.modal-body {
replaced with `NarrowModal`. No more external styles for modal.

2020-09-28 17:24 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionForm.tsx
> +            <ModalFooter className={styles.footer}>
replaced with `NarrowModal`. Here I didn't use footer prop because it reduces flexibility. Now we compose header and footer using separate components.

2020-09-28 17:24 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionModal.module.scss
> +  @include media-breakpoint-down(sm) {
used `NarrowModal`

2020-09-28 18:05 UTC, arjunu commented on packages/web/app/components/governance/proposal/UploadVotingResultsModal.module.scss
> +.total-error {
done

2020-09-28 19:01 UTC, arjunu commented on packages/web/app/modules/tx/transactions/shareholder-resolution-vote/offchain-votes-upload/sagas.ts
> +    etoModuleApi.selectors.selectEtoContract(state, etoPreviewCode),
done

2020-09-28 19:03 UTC, arjunu commented on packages/web/app/modules/tx/transactions/shareholder-resolution-vote/setup/sagas.ts
> +    etoModuleApi.selectors.selectEtoContract(state, etoPreviewCode),
done

2020-09-28 19:11 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-view/sagas.ts
> +  yield put(globalActions.etoFlow.loadIssuerEto());
moved to `getShareCapital`

2020-09-28 19:17 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-setup/sagas.ts
> +  const eto: TEtoSpecsData | undefined = yield* select(selectIssuerEto);
added error handling

2020-09-28 19:26 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionModal.module.scss
> +.link {
used Button Inline

2020-09-28 19:31 UTC, arjunu commented on packages/web/app/components/issuer-dashboard/voting/NewVotingResolutionModal/NewVotingResolutionModal.module.scss
> +  display: block;
changed to flex

2020-09-29 09:24 UTC, arjunu commented on packages/web/app/modules/shareholder-resolutions-voting-setup/sagas.spec.ts
> +    container = moduleSetup.container;
updated

2020-09-29 19:47 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/shareholder-resolution-vote-offchain-votes-upload/ShareholderResolutionVoteOffChainVotesUploadSummary.tsx
> +export const ShareholderResolutionVoteOffchainVotesUploadSummaryLayout: React.FunctionComponent<TStateProps &
kept it since we don't have design for this

2020-09-30 10:05 UTC, desfero commented on packages/web/intl/locales/en-en.json
> +  "shareholder-resolution-widget.text": "Create a new shareholder resolution you require your tokenholders to vote on.",
ok, in retrospection is sounds valid to me too :D

2020-10-01 07:12 UTC, desfero commented on packages/web/app/components/modals/tx-sender/shareholder-resolution-vote-setup/ResolutionPublishSuccessModal.tsx
> +              <a
We should use `ExternalLink` to keep control of any kind of links that are outside our router. Also, it should be marked as `target="_blank"`

2020-10-01 07:15 UTC, desfero commented on packages/web/app/components/settings/verify-email/AccountSetupVerifyEmailComponent.tsx
> +          <FormattedMessage id="form.button.CONTINUE" />
ok, let's convert then to only use normal case naming. Lower case if needed should be handled by css, not by translation files

2020-10-01 08:05 UTC, desfero commented on packages/web/app/components/shared/UploadedFiles.module.scss
> +  & path {
`currentColor` should be applied to `delete.svg` :)

2020-10-05 10:56 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/shareholder-resolution-vote-setup/ResolutionPublishSuccessModal.tsx
> +              <a
Used Link with relative URL but for display I had to keep `selectBaseUrl` because relative link looks weird.

2020-10-05 10:57 UTC, arjunu commented on packages/web/cypress.json
> +  "viewportHeight": 1080
by default the height is some 600 and some tests like the ones involving investment modal isn't responsive below some 800px and therefore fail.

2020-10-05 13:04 UTC, desfero submitted a review, later dismissed

2020-10-07 15:04 UTC, glupiawymowka approved these changes
both new voting and final resolution are working. some minor issue fixes to be requested in a new ticket

2020-10-07 15:12 UTC, merged