#4364 introduce create module util
Neufund/platform-frontend pull request #4580
Opened 2020-09-17 13:55 UTC by desfero

**Technical notes**
This pr adds unit tests for our module system type utils and also introduces `createModuleSetup` utility helper.

In general `createModuleSetup` is just an identity function that provides type narrowing and type checking.
In the future it can also check in `dev` mode if all modules have a unique id. Can also we used in #4426 to handle dependencies that are transitive.

2020-09-22 17:14 UTC, arjunu requested changes
There a couple of web modules that use the module system and should use `createModuleSetup`.

2020-09-28 07:56 UTC, arjunu approved these changes

2020-09-29 15:01 UTC, Moejoe90 approved these changes
Looks good from my side

2020-09-29 15:17 UTC, AlexeyTuboltsev approved these changes

2020-09-29 19:16 UTC, merged