Replace EtherscanTxLink with EtherscanAddressLink for addresses
Neufund/platform-frontend pull request #4594
Opened 2020-09-30 10:53 UTC by arjunu

2020-10-01 12:58 UTC, Moejoe90 requested changes
one question

2020-10-01 12:58 UTC, Moejoe90 commented on packages/web/app/components/shared/links/EtherscanLink.tsx
> +  address: string | EthereumAddress | EthereumAddressWithChecksum;
what stops us from making this change already?

2020-10-01 13:01 UTC, arjunu commented on packages/web/app/components/shared/links/EtherscanLink.tsx
> +  address: string | EthereumAddress | EthereumAddressWithChecksum;
it's a big change, we can do it as a separate ticket.

2020-10-01 16:09 UTC, glupiawymowka approved these changes

2020-10-02 10:26 UTC, Moejoe90 approved these changes

2020-10-05 08:05 UTC, merged