Make the Confirm Password field always visible
Neufund/platform-frontend pull request #4602
Opened 2020-10-01 12:53 UTC by arjunu

2020-10-01 13:17 UTC, andywalton approved these changes
Looks good to me Arjun.

2020-10-01 19:39 UTC, desfero requested changes
What about 
```
Also, let's turn off autocomplete for a password (https://web.dev/sign-in-form-best-practices/#autofill)
```

2020-10-04 18:25 UTC, desfero approved these changes

2020-10-05 11:19 UTC, glupiawymowka approved these changes

2020-10-05 11:24 UTC, merged