Run Wallet tests on Browserstack through CI
Neufund/platform-frontend pull request #4773
Opened 2021-01-28 12:11 UTC by arjunu

~Blocked by #4762 and #4771~

2021-02-17 08:16 UTC, desfero requested changes
Looks really cool. I left some small suggestions and questions

2021-02-17 08:16 UTC, desfero commented on packages/wallet/app/components/utils/testIds.ts
> +    recoveryPhrase: "AccountBackupScreen_recoveryPhrase_",
do we need last `_`?

2021-02-17 08:16 UTC, desfero commented on packages/wallet/appcenter-post-build.sh
> +if [ "$APP_CENTER_CURRENT_PLATFORM" == "android" ]; then
Hm, what if we use platform-specific env variables `APPCENTER_XCODE_PROJECT` (https://docs.microsoft.com/en-us/appcenter/build/custom/variables/) and see if it's ios or android build?

2021-02-17 08:16 UTC, desfero commented on packages/wallet/appcenter-pre-build.sh
> +if [ -z "$APP_CENTER_CURRENT_PLATFORM" ]
If we use platform-specific variables then this check is not needed

2021-02-17 16:33 UTC, arjunu commented on packages/wallet/app/components/utils/testIds.ts
> +    recoveryPhrase: "AccountBackupScreen_recoveryPhrase_",
because after _ the word no. is appended
`AccountBackupScreen_recoveryPhrase_0`

2021-02-24 18:09 UTC, arjunu commented on .circleci/browserstack-test-e2e.sh
> +    if [[ "$APP_NAME" == "neufund-wallet-mvp" ]]; then
The App Center API calls are platform specific so we need to use `$APP_NAME` anyway

2021-02-24 18:14 UTC, arjunu commented on packages/wallet-e2e/config/browserstack/wdio.shared.browserstack.config.js
> +delete config.port;
I tried `...config, port: undefined` but it still complains. It doesn't want this key. `delete` won't cause any issues because if we import config into another file then this file won't run so port isn't deleted

2021-02-24 18:15 UTC, arjunu commented on packages/wallet-e2e/package.json
> +    "test:e2e:ios:local": "./node_modules/.bin/wdio ./config/local/wdio.ios.local.config.js",
udpated

2021-02-24 21:54 UTC, arjunu commented on packages/wallet/appcenter-pre-build.sh
> +if [ -z "$APP_CENTER_CURRENT_PLATFORM" ]
removed

2021-02-24 21:54 UTC, arjunu commented on packages/wallet/appcenter-post-build.sh
> +if [ "$APP_CENTER_CURRENT_PLATFORM" == "android" ]; then
Used `APPCENTER_XCODE_PROJECT`

2021-02-24 21:54 UTC, arjunu commented on .circleci/config.yml
> +      - restore_cache:
removed

2021-02-25 12:29 UTC, desfero approved these changes

2021-02-25 13:03 UTC, merged