Issuer dashboard copy changes
Neufund/platform-frontend pull request #4788
Opened 2021-02-15 15:18 UTC by arjunu

2021-02-16 09:23 UTC, desfero requested changes

2021-02-16 09:23 UTC, desfero commented on packages/web/app/components/modals/wallet-access/AccessWallet.tsx
> +  invariant(walletType, "Wallet type should be defined");
is there a need for that? I see we have `assertNever` on line 139

2021-02-16 09:23 UTC, desfero commented on packages/web/app/components/settings/kyc-states/KycStatusWidget.tsx
I would say we should split that by 2 separate components right now we have a ton of ifs here. 
Would be good to have KycInvestorStatusWidget, KycIssuerStatusWidget. Also what about Nominee?

2021-02-16 09:23 UTC, desfero commented on packages/web/intl/locales/en-en.json
> +  "settings.kyc-status-widget.status.pending.individual": "Thank you for submitting your idensettings.kyc-status-widget.status.ignoredtity verification request! We will review it within 2-3 business
`Thank you for submitting your idensettings.kyc-status-widget.status.ignoredtity verification request` some typo

2021-02-16 09:23 UTC, desfero commented on packages/web/intl/locales/en-en.json
> +  "settings.kyc-status-widget.status.rejected.issuer": "We regret to inform you that after careful review, your account verification request has been rejected. To contact Customer Care, please click
Is there a reason we duplicate all strings here even when they are equal?

2021-02-16 14:13 UTC, arjunu commented on packages/web/app/components/modals/wallet-access/AccessWallet.tsx
> +  invariant(walletType, "Wallet type should be defined");
replaced with `nonNullable`

2021-02-16 14:17 UTC, arjunu commented on packages/web/app/components/settings/kyc-states/KycStatusWidget.tsx
Nominee stays same as before, we will change it later it seems.

2021-02-16 14:57 UTC, arjunu commented on packages/web/app/components/settings/kyc-states/KycStatusWidget.tsx
Used `isIssuer` condition inside strings so most of them are removed from here now

2021-02-16 14:58 UTC, arjunu commented on packages/web/intl/locales/en-en.json
> +  "settings.kyc-status-widget.status.pending.individual": "Thank you for submitting your idensettings.kyc-status-widget.status.ignoredtity verification request! We will review it within 2-3 business
Oops fixed

2021-02-17 13:14 UTC, desfero submitted a review, later dismissed

2021-03-05 10:53 UTC, glupiawymowka approved these changes

2021-03-05 10:53 UTC, merged