CI run jobs only for changed packages
Neufund/platform-frontend pull request #4791
Opened 2021-02-16 18:29 UTC by arjunu

2021-02-17 14:33 UTC, arjunu commented on packages/design-system/src/components/buttons/Button.tsx
> -              */}
dummy change for testing

2021-02-17 15:53 UTC, arjunu commented on .circleci/monorepo.json
> +{
@desfero I didn't include all files from the root. Just ".circleci", "yarn.lock", and  "package.json" because we have README, LICENSE etc so whitelisting is easier than blacklisting

2021-02-23 14:59 UTC, desfero requested changes

2021-02-23 14:59 UTC, desfero commented on .circleci/monorepo.json
> +      ":!packages/**/*.md"
is that excluding md files? What about running md files though linter?

2021-02-23 14:59 UTC, desfero commented on packages/design-system/src/components/buttons/Button.tsx
> -              */}
can be reverted now?

2021-02-23 14:59 UTC, desfero commented on .circleci/config.yml
> +                command: source /opt/circleci/.nvm/nvm.sh && yarn workspace @neufund/web show-tags
show tags duplicated?

2021-02-23 14:59 UTC, desfero commented on .circleci/config.yml
>            requires:
Is it possible to move that as a comman/job that will have a parameter `preflight_checks` and `deploy-storybook`? So we kinda don't duplicate the same code twice?

2021-02-23 15:58 UTC, arjunu commented on .circleci/config.yml
> +                command: source /opt/circleci/.nvm/nvm.sh && yarn workspace @neufund/web show-tags
removed

2021-02-23 15:59 UTC, arjunu commented on packages/design-system/src/components/buttons/Button.tsx
> -              */}
Prettier didn't complain so I left, reverted it now

2021-02-23 17:33 UTC, arjunu commented on .circleci/monorepo.json
> +      ":!packages/**/*.md"
removed

2021-02-23 17:35 UTC, arjunu commented on .circleci/config.yml
>            requires:
Setting a cron trigger makes the workflow not run without it. I moved artifacts check into install job like you did with condition. Nightly is still duplicated with trigger and storybook job

2021-02-24 08:02 UTC, desfero approved these changes

2021-02-24 12:25 UTC, merged