#4419 Add push notifications switch
Neufund/platform-frontend pull request #4793
Opened 2021-02-17 13:12 UTC by desfero

2021-03-09 16:13 UTC, arjunu commented on packages/wallet/android/build.gradle
> +        classpath('com.android.tools.build:gradle:4.1.0')
Do we need gradle v4 for this to work? Go to build page on AppCenter and it says "Usage of Android Gradle Plugin 4.1.0+ is not supported at the moment. Please use any of the earlier versions."

2021-03-09 16:36 UTC, arjunu commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +      <BottomSheetModal isVisible={versionPressCount === 3}>
The bottom is curved on my android phone
![image](https://user-images.githubusercontent.com/4038217/110504868-e1e69b80-80fd-11eb-900e-0e3cbea3a369.png)

2021-03-09 16:37 UTC, arjunu commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +      return <ProfileLayout {...rest} />;
what's this for if there's no loading skeleton animation for loading?

2021-03-09 16:39 UTC, arjunu commented on packages/wallet/app/components/shared/forms/layouts/Switch.tsx
> +  <NativeSwitch ref={ref} {...props} />
I think there's a bug with the component, in storybook when I toggle it, for a second it switches to the other state and comes back to default state

2021-03-09 16:42 UTC, arjunu commented on packages/wallet/app/modules/device-information/DeviceInformation.ts
> +    return Promise.resolve(getBuildId());
Gets build number of the operating system.
https://github.com/react-native-device-info/react-native-device-info#getbuildid
why OS?

2021-03-09 16:43 UTC, arjunu commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +      <BottomSheetModal isVisible={versionPressCount === 3}>
All `BottomSheetModal`s have this issue. I rem seeing it before.

2021-03-09 16:46 UTC, arjunu commented on packages/wallet/app/modules/eth/lib/EthWalletFactory.ts
> +      } catch (e) {
cool, which issue is this for?

2021-03-09 16:53 UTC, arjunu commented on packages/wallet/app/modules/notifications/module.ts
>  import { createModuleSetup } from "@neufund/shared-modules";
would it better to call this module `push-notifications`?

2021-03-09 16:55 UTC, arjunu commented on packages/wallet/app/modules/profile-screen/sagas.ts
> +function* toogleNotifications(): SagaGenerator<void> {
typo should be `toggleNotifications`

2021-03-09 16:57 UTC, arjunu commented on packages/wallet/app/modules/profile-screen/sagas.ts
> +      case ENotificationPermissionStatus.DENIED:
there's a bug here on Android. Turn on push notifications in Profile screen, go to Neufund App settings -> Disable notifications -> come back to app and try to enable push notifications and it shows this Alert. 

Now go to Neufund App settings -> Enable notifications -> come back to app and try to enable push notifications -> it shows the alert even though it's already enabled. If I click cancel I see that the toggle was successfully switched to on

2021-03-10 12:11 UTC, arjunu commented on packages/wallet/app/modules/notifications/lib/symbols.ts
> +  notificationsProvider: createLibSymbol<FirebaseProvider>("notificationsProvider"),
notificationsProvider is used only by `NotificationsManager` so why make it a non-private symbol? We don't expect to use it in sagas do we?

2021-03-10 12:13 UTC, arjunu commented on packages/wallet/app/modules/notifications/sagas.ts
> +export function* notificationsSagas(): SagaGenerator<void> {
I really like this style of saga organisation as opposed to all sagas in one file

2021-03-10 12:25 UTC, arjunu commented on packages/wallet/app/modules/notifications/sagaFunctions/disableNotifications.ts
> +      call([notificationsConfigStorage, "set"], {
what about abstracting notificationsConfigStorage get and set behind a class? 
maybe in notification manager? 

```
yield* call([notificationsManager, "clearConfig"]);
```

2021-03-10 12:31 UTC, arjunu commented on packages/wallet/app/modules/notifications/actions.ts
> +  tryToDropSession: createActionFactory("NOTIFICATIONS_TRY_TO_TROP_SESSION"),
Typo with `DROP`

2021-03-10 13:15 UTC, arjunu commented on packages/wallet/app/modules/profile-screen/selectors.ts
> +const selectProfileScreenData = createSelector(
nice we should follow this going forward

2021-03-10 14:21 UTC, arjunu commented on packages/wallet/app/modules/notifications/lib/NotificationsManager.ts
> +    this.removeAllListeners();
also `notificationManager.disable`

2021-03-10 14:22 UTC, arjunu requested changes
Few comments and questions

2021-03-10 14:22 UTC, arjunu commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +      <BottomSheetModal isVisible={versionPressCount === 3}>
maybe we create a ticket for tihs?

2021-03-10 14:38 UTC, arjunu commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +      <BottomSheetModal isVisible={versionPressCount === 3}>
open this modal, go to home screen, come back and modal is still open

2021-03-10 14:40 UTC, arjunu commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +      <BottomSheetModal isVisible={versionPressCount === 3}>
turn off notifications and modal still opens sometimes.
![image](https://user-images.githubusercontent.com/4038217/110646099-d99e6700-81b6-11eb-9d6f-de765a3ac8e2.png)

2021-03-11 08:19 UTC, desfero commented on packages/wallet/android/build.gradle
> +        classpath('com.android.tools.build:gradle:4.1.0')
reverted

2021-03-12 10:34 UTC, desfero commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +  const optimisticallyAreNotificationsAllowed = isNotificationsPermissionChangeInProgress
fixed

2021-03-12 10:37 UTC, desfero commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +      <BottomSheetModal isVisible={versionPressCount === 3}>
Will do a separate ticket for button layout, 
but given its app info modal that is not should not be used by customers, we can IMO leave other bugs (like it's okay to keep the modal open after you moved to home and back to profile)

2021-03-12 10:39 UTC, desfero commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +      return <ProfileLayout {...rest} />;
it's in general for consistency with other screen as they all have 4 states (loading/ready/refreshing/error). For profile screen `loading/ready/refreshing` states are the same but that may also change in the future if we load some screen-specific data

2021-03-12 10:51 UTC, desfero commented on packages/wallet/app/components/shared/forms/layouts/Switch.tsx
> +  <NativeSwitch ref={ref} {...props} />
Because it's a controlled component and the state is constant. Given it's a native component animation happens there on tap so that's why you see flickering

2021-03-12 11:53 UTC, desfero commented on packages/wallet/app/modules/device-information/DeviceInformation.ts
> +    return Promise.resolve(getBuildId());
oh, good catch, fixed

2021-03-12 11:55 UTC, desfero commented on packages/wallet/app/modules/device-information/DeviceInformation.spec.ts
> +    const buildId = await deviceInformation.getAppBuildId();
fixed

2021-03-12 12:03 UTC, desfero commented on packages/wallet/app/modules/eth/lib/EthWalletFactory.ts
> +      } catch (e) {
it happened to me once or twice with the error that keychain error occurred please restart your phone

2021-03-12 14:47 UTC, desfero commented on packages/wallet/app/modules/notifications/module.ts
>  import { createModuleSetup } from "@neufund/shared-modules";
good point, done

2021-03-12 15:17 UTC, desfero commented on packages/wallet/app/modules/profile-screen/sagas.ts
> +      case ENotificationPermissionStatus.DENIED:
i changed the logic a little bit, please check again

2021-03-12 15:19 UTC, desfero commented on packages/wallet/app/modules/notifications/lib/symbols.ts
> +  notificationsProvider: createLibSymbol<FirebaseProvider>("notificationsProvider"),
everything here can be marked as `privateSymbol` given it's not used outside a module

2021-03-12 15:21 UTC, desfero commented on packages/wallet/app/modules/notifications/sagaFunctions/disableNotifications.ts
> +      call([notificationsConfigStorage, "set"], {
hm, not sure `NotificationsManager` should control the storage given its only UI related

2021-03-21 13:07 UTC, desfero commented on packages/wallet/app/modules/notifications/lib/NotificationsManager.ts
> +    this.removeAllListeners();
i did some refactoring to the logic

2021-03-29 09:46 UTC, arjunu commented on packages/wallet/app/modules/init/sagas.ts
> +import { EPushNotificationPermissionStatus } from "modules/push-notifications/types";
should we do a convention of re-exporting everything in a module via index.js?
For example if `modules/push-notifications/index.js` re-exports `EPushNotificationPermissionStatus`, we can do `import { EPushNotificationPermissionStatus } from "modules/push-notifications"` ?

2021-03-29 09:47 UTC, arjunu commented on packages/wallet/app/modules/init/sagas.ts
> +import { EPushNotificationPermissionStatus } from "modules/push-notifications/types";
It adds extra work for reexporting but this way we don't have to worry about where to import something from. Maybe the side effect is IDE could also get confused :P

2021-03-29 10:40 UTC, arjunu commented on packages/wallet/app/components/screens/ProfileScreen/ProfileScreen.tsx
> +          <Pressable onPress={() => setVersionPressCount(count => count + 1)}>
Clamp to 3 https://lodash.com/docs/4.17.15#clamp

2021-03-29 10:44 UTC, arjunu commented on packages/wallet/app/modules/push-notifications/sagas.ts
> +  yield takeLeading(
Open app, enable notifications if not already enabled.
Now go to app settings and turn off notifications permission.
Come back to app and go to profile screen, notifications is still on.
I tried to debug, initAuthSigned executes after unlocking app but tryToSubscribeToNotificationEvents never runs

2021-03-30 11:46 UTC, arjunu approved these changes

2021-03-31 14:37 UTC, merged