Show tx costs value for insufficient ETH
Neufund/platform-frontend pull request #4797
Opened 2021-02-18 13:22 UTC by arjunu

2021-02-23 07:18 UTC, desfero requested changes
Some small changes

2021-02-23 07:18 UTC, desfero commented on packages/web/app/modules/tx/validator/sagas.ts
> +  yield put(actions.txValidator.setGasValidationInfo(convertFromUlps(costUlps).toString()));
i see that we need some refactoring to be done here in the future. 
For e.g we can refactor validation `notifications` to have also a payload and then don't throw an error but rather put a `NOT_ENOUGH_GAS` as a validation notification.

2021-02-23 07:18 UTC, desfero commented on packages/web/app/modules/tx/validator/selectors.ts
> +export const selectTxValidatorGasCostEur = (state: TAppGlobalState) => {
that's a good example for `createSelector` to memorize and don't rerun `convertFromUlps,multiplyBigNumbers` multiple times

2021-02-23 07:18 UTC, desfero commented on packages/web/app/test-e2e/investor/wallet/withdraw/Withdraw.spec.e2e.io.ts
> +        (ethBalance + 1).toString(),
let's move `ethBalance + 1` as a variable `ethBalanceAboveMax`

2021-02-23 12:25 UTC, arjunu commented on packages/web/app/modules/tx/validator/selectors.ts
> +export const selectTxValidatorGasCostEur = (state: TAppGlobalState) => {
updated

2021-02-23 12:25 UTC, arjunu commented on packages/web/app/test-e2e/investor/wallet/withdraw/Withdraw.spec.e2e.io.ts
> +        (ethBalance + 1).toString(),
updated

2021-02-23 12:28 UTC, arjunu commented on packages/web/app/modules/tx/validator/sagas.ts
> +  yield put(actions.txValidator.setGasValidationInfo(convertFromUlps(costUlps).toString()));
Ok I added a TODO. It is a big change since we both sender saga and validator saga expects it to throw and we are showing the error in the UI

2021-02-23 15:02 UTC, desfero submitted a review, later dismissed

2021-02-24 20:17 UTC, glupiawymowka commented
hey, looks like there's something wrong with displaying the value in ETH. 
<img src="https://user-images.githubusercontent.com/18315589/109060031-3264fe80-76e5-11eb-91a0-d18ab861590c.png" width="400">

sorry for Polish :D But it basically shows that 5.81€ is 0.0044 ETH and not <0.0001, while 0.0001 is actually 0.13€
<img src="https://user-images.githubusercontent.com/18315589/109060229-72c47c80-76e5-11eb-9aec-ec34eaad503c.png" width="400">

2021-02-25 07:58 UTC, desfero approved these changes

2021-02-25 10:52 UTC, glupiawymowka approved these changes

2021-02-25 10:52 UTC, merged