Android Biometrics support
Neufund/platform-frontend pull request #4806
Opened 2021-02-26 12:21 UTC by arjunu

2021-03-02 16:08 UTC, arjunu commented on packages/wallet/app/modules/biometrics/sagas.ts
> +    // assume Fingerprints are available
because I don't think there is an Android phone with Face recognition but no Fingerprint

2021-03-02 16:10 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/Biometrics.ts
> +    this.logger.info(`Security level is "${securityLevel || "null"}"`);
linter forced me to `|| "null"` here

2021-03-02 16:11 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/SecureStorage/KeychainSecureStorage.ts
> +      accessControl: ACCESS_CONTROL.BIOMETRY_CURRENT_SET_OR_DEVICE_PASSCODE,
I had to change this from USER_PRESENCE because that doesn't work on Android

2021-03-04 13:18 UTC, desfero requested changes

2021-03-04 13:18 UTC, desfero commented on packages/wallet/app/modules/biometrics/sagas.ts
> +  const biometricsAvailableButNotSet =
but if biometrics are available but not set yet shouldn't we put `actions.noBiometricsAccess`?

2021-03-04 13:18 UTC, desfero commented on packages/wallet/app/modules/biometrics/sagas.ts
> +  const biometricsAvailableButNotSet =
or maybe we should do another state `EBiometricsState.NO_SETUP` that will handle the case where there is support in the device but not yet setup was done by user.

Then we can refactor a little bit this:
https://github.com/Neufund/platform-frontend/blob/2b22ae757a163d95e347710249df47ad7772bbc7/packages/wallet/app/components/screens/NoBiometricsScreen/NoBiometricsScreen.tsx#L44-L55

In a way where current UI for `NO_SUPPORT` is moved under `NO_SETUP` and what's inside if `if(biometricsType === BIOMETRICS_NONE)` is used for `NO_SUPPORT` case. 

What do you think? Should make the code more readable and now we have a separate enum for all cases

2021-03-09 12:08 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/Biometrics.ts
> +    this.logger.info(`Security level is "${securityLevel || "null"}"`);
good idea, updated

2021-03-09 12:11 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/Biometrics.ts
> +    return (await this.getSecurityLevel()) !== null;
https://github.com/oblador/react-native-keychain/blob/19a1ab8e486e300c234ce6a5ed9aabb1aceda43e/typings/react-native-keychain.d.ts#L137

2021-03-09 12:16 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/SecureStorage/KeychainSecureStorage.ts
> +      return null;
Typescript won't let me as the return type is `false | SharedWebCredentials`. Changed it to `return result !== false ? result.password : null;`

2021-03-09 12:42 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/Biometrics.ts
> +    if (isIOS) {
updated

2021-03-09 13:11 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/Biometrics.ts
> +      return new KeychainSecureStorage(await this.getSecurityLevel());
Because on emulators the default is `SECURE_SOFTWARE`. Ok I forced it to Software only for emulators and default is hardware now

2021-03-09 13:30 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/SecureStorage/KeychainSecureStorage.ts
> +            ToastAndroid.show(
moved Toast logic to auth module `signInExistingAccount` saga

2021-03-09 14:01 UTC, arjunu commented on packages/wallet/app/modules/biometrics/module.ts
> +  CACHE_TIMEOUT,
It's was used in EthSecureEnclave tests. I see we're testing cache timeout in SecureStorage.spec and since it's internals to this module, removed it

2021-03-09 14:02 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/symbols.ts
> +export const symbols = {
Created and used `symbols.secureStorageProvider`

2021-03-09 14:33 UTC, arjunu commented on packages/wallet/app/modules/biometrics/lib/SecureStorage/KeychainSecureStorage.ts
> +      accessControl: ACCESS_CONTROL.BIOMETRY_CURRENT_SET_OR_DEVICE_PASSCODE,
ok keeping this as it is

2021-03-09 15:36 UTC, arjunu commented on packages/wallet/app/modules/auth/sagas.spec.ts
> +    setupPermissionsModule(),
moved to biometrics setup

2021-03-09 15:37 UTC, arjunu commented on packages/wallet/app/modules/biometrics/sagas.ts
> +  const biometricsAvailableButNotSet =
created and used `NOT_SETUP` state

2021-03-10 18:48 UTC, desfero submitted a review, later dismissed

2021-03-15 12:36 UTC, glupiawymowka commented
looks like the app doesn't refresh on biometrics delete/add. 
On Android 9 at least, this allows me to freely unlock the Neufund Wallet once the Fingerprint is deleted. Restarting the app helps. 
Steps to reproduce:
1. Create/import a wallet
2. In the device settings, delete Fingerprint
3. Open the app and try to unlock 

Also adding the fingerprint is not read by the app automatically and the user needs to close it completely and start over to get rid of the "add biometrics" screen

2021-03-28 17:10 UTC, desfero approved these changes
Issues @glupiawymowka mentioned will be moved to separate ticket as it's both ios and android

2021-03-28 17:10 UTC, merged