Add some dev scripts
Neufund/platform-frontend pull request #4813
Opened 2021-03-03 12:28 UTC by arjunu

2021-03-03 12:31 UTC, arjunu commented on package.json
> +    "node_modules:reinstall": "./dev-scripts/reinstall-node-modules.sh",
I'm adding a convention with `dev-scripts` directory as a directory that contains only scripts used by developers locally and never on CI

2021-03-03 12:35 UTC, arjunu commented on packages/wallet/package.json
> -    "postinstall": "patch-package",
If I'm not wrong this `patch-package` isn't used because this `postinstall` is called only if we do `yarn` inside `packages/wallet` and not the root

2021-03-03 12:37 UTC, arjunu commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +#!/usr/bin/env bash
I will add an iOS script in future. iOS build takes too long. Since Android is faster I'd prefer to test this

2021-03-03 17:10 UTC, arjunu commented on .circleci/config.yml
> +            - mobile_ios_build-success
I forgot to add mobile e2e jobs for nightly

2021-03-22 18:33 UTC, desfero requested changes
Looks cool just some questions

2021-03-22 18:33 UTC, desfero commented on packages/wallet/dev-scripts/install-pods.sh
> +    read -r -p "Reinstall correct version?? (y/n): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1
hm, can we branch the logic here because during `yarn install` developer would not expect any questions to be asked by command line prompt? Maybe in the case of `preinstall` we can fail the job if it's not the same and in the case of `install pods command ask that question?

2021-03-22 18:33 UTC, desfero commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +  source ./scripts/.env
maybe for consistency we can keep `.env` in the root of `wallet-e2e` package?

2021-03-22 18:33 UTC, desfero commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +  cd ../wallet || exit 1
Why do we need `|| exit 1`?

2021-03-22 18:33 UTC, desfero commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +  cd ../wallet || exit 1
Also maybe we can use somehow over `cd` `yarn workspace @neufund/wallet build` or something like this?

2021-03-22 18:33 UTC, desfero commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +upload_apk_to_browserstack() {
let make it in a way that this function receives path to apk as a parameter

2021-03-22 18:33 UTC, desfero commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +  upload_apk_response=$(upload_apk_to_browserstack)
and to not `cd` we can pass `upload_apk_response=$(upload_apk_to_browserstack(app/build/outputs/apk/release/app-release.apk))`

2021-03-22 18:33 UTC, desfero commented on dev-scripts/reinstall-node-modules.sh
> +yarn workspace @neufund/wallet clean &&
would be cool if we can do `wsrun clean` as a new script called `clean` in root `package.json` as it can be handy in the future and here we can just call that. Then we don't have any strict dependency to any package here

2021-03-29 13:47 UTC, arjunu commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +  upload_apk_response=$(upload_apk_to_browserstack)
if build failed or if `cd app/build/outputs/apk/release` doesn't exist then cd will exit with code 1

2021-03-29 13:49 UTC, arjunu commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +  cd ../wallet || exit 1
`|| exit 1` because if target directory doesn't exist it then script won't crash and continues to execute next line.

2021-03-29 14:22 UTC, arjunu commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +  source ./scripts/.env
done

2021-03-29 14:22 UTC, arjunu commented on dev-scripts/reinstall-node-modules.sh
> +yarn workspace @neufund/wallet clean &&
done

2021-03-29 14:23 UTC, arjunu commented on packages/wallet/dev-scripts/install-pods.sh
> +    read -r -p "Reinstall correct version?? (y/n): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1
updated

2021-03-29 14:27 UTC, arjunu commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +  cd ../wallet || exit 1
replaced with `e2e:build:android-release`

2021-03-29 14:27 UTC, arjunu commented on packages/wallet-e2e/dev-scripts/local-browserstack-run.sh
> +  upload_apk_response=$(upload_apk_to_browserstack)
replaced with full path

2021-03-29 14:31 UTC, arjunu commented on packages/design-system/package.json
> +    "clean": "echo Nothing to clean",
in future we can add dist cleanup here

2021-03-30 18:42 UTC, desfero commented on packages/design-system/package.json
> +    "clean": "echo Nothing to clean",
yeah exactly, that's why i wanted to have a root clean job already in place

2021-03-30 18:45 UTC, desfero approved these changes

2021-03-30 18:45 UTC, merged