ETO Fundraising Statistics
Neufund/platform-frontend pull request #4820
Opened 2021-03-11 12:27 UTC by arjunu

2021-03-15 19:44 UTC, arjunu commented on packages/shared-modules/src/index.ts
>  export * from "./modules/wallet/module";
just alphabetical sorting

2021-03-15 19:44 UTC, arjunu commented on packages/shared-utils/src/index.ts
> +export * from "./opaque-types";
alphabetical sorting

2021-03-15 19:45 UTC, arjunu commented on packages/shared-utils/src/utils/DateUtils.ts
> +  return `${stringDays}:${stringHours}:${stringMinutes}:${stringSeconds}`;
Moment JS seems to be able to not do this. Plugins have to be used. Since we have a plan to move away from moment, I used this

2021-03-15 19:46 UTC, arjunu commented on packages/shared-utils/src/utils/fileUtils.ts
> +export const createCsvDataUri = (dataAsString: string) =>
`createCsvDataUri` & `downloadFile` moved from web package

2021-03-20 13:11 UTC, Moejoe90 reviewed
left a couple of questions

2021-03-20 13:11 UTC, Moejoe90 commented on packages/web/app/test-e2e/issuer/eto/view/FundraisingStatistics.spec.e2e.io.ts
> +  cy.get(tid("eto.public-view.fundraising-statistics.view")).should("exist");
:1st_place_medal:

2021-03-20 13:11 UTC, Moejoe90 commented on packages/web/app/modules/eto-view/shared/sagas.ts
> +  const stats = yield* select(state => analyticsModuleApi.selectors.selectEtoStats(state, etoId));
could there be a case where the selector will return undefined?

2021-03-20 13:11 UTC, Moejoe90 commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
>    React.useEffect(() => {
do you guys have a clear guide when to use recompose and when to use hooks?

2021-03-23 19:18 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/types.ts
> +  // TODO define structure when we do graphs
I have already added the types in my graph PR https://github.com/Neufund/platform-frontend/pull/4823/

2021-03-23 19:21 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
>    React.useEffect(() => {
In web app we have generally used route actions for loading data but here in this case one route is reused for all types of users: investor. issuer, nominee, unauth user and there's eto by ID and eto by preview code routes so I didn't want to repeat the same action for every route. In wallet app we are using `React.useEffect` so I will check this with @desfero when he's back

2021-03-23 19:27 UTC, arjunu commented on packages/web/app/modules/eto-view/shared/sagas.ts
> +  const stats = yield* select(state => analyticsModuleApi.selectors.selectEtoStats(state, etoId));
actually yeah dunno why TS didn't complain, ok I added `nonNullable`

2021-03-23 19:34 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/selectors.ts
> +  selectAnalyticsState(state).stats[etoId];
added `nonNullable` in saga, it won't crash in the UI

2021-03-29 14:31 UTC, desfero requested changes
Some small bugs not fully related to the changes:

![image](https://user-images.githubusercontent.com/7031578/112852349-21285c80-90ac-11eb-9572-4b2626865c8f.png)
Tabs are not in sync with zeplin

2021-03-29 14:31 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +        <Panel columnSpan={EColumnSpan.THREE_COL}>
columnSpan not needed

2021-03-29 14:31 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +      <Container columnSpan={EColumnSpan.THREE_COL}>
columntSpan not nedeed

2021-03-29 14:31 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +                  {stats.equityTokensCreated} {equityTokenSymbol}
For that we have to create a new currency formatter `EquityToken` and pass symbol and value

2021-03-29 14:31 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +                  {stats.equityTokensCreated} {equityTokenSymbol}
Check the `Equity` component of the mobile app for example

2021-03-29 14:31 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +                    separator: <>&nbsp;</>,
why we don't just manually put space in translation?

2021-03-29 14:31 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +                    eur: <Eth value={stats.equityTokenPriceAverage} noSymbol />,
so it's probably `Eur` not eth given the translation file. We can also remove EUR from translation and remove `noSymbol` here

2021-03-29 14:31 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +                    separator: <>&nbsp;</>,
the same for all other places where we use nbsp

2021-03-29 14:31 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +          <div>
That's why I'm not a fan of using the display grid as it introduces some nesting that can be confusing for other devs later.

2021-03-29 14:31 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +          <div className={styles.timeframeStats}>
![image](https://user-images.githubusercontent.com/7031578/112852218-03f38e00-90ac-11eb-950a-3163239d04f8.png)
For tables can we have two blocks in a row so we don't waste a lot of space?

2021-03-30 17:03 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +      <Container columnSpan={EColumnSpan.THREE_COL}>
removed

2021-03-30 17:03 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +        <Panel columnSpan={EColumnSpan.THREE_COL}>
removed

2021-03-30 17:03 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +  label: string | TTranslatedString;
removed

2021-03-30 17:20 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/selectors.ts
> +  selectAnalyticsState(state).stats[etoId];
but here it's a simple accessor, no logic and no transformation. Also Reselect doesn't have built-in support for creating selectors that accepts arguments

2021-03-30 17:23 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/lib/AnalyticsApi.ts
> +const STATS_PATH = "/stats";
super, updated

2021-03-30 17:38 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/lib/AnalyticsApi.ts
> +        url: `${ETOS_PATH}/${etoId}/${STATS_PATH}`,
added

2021-03-30 17:39 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/sagas.ts
> +  const { analyticsApi: analyticsApiService } = yield* neuGetBindings({
updated

2021-03-30 17:41 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/sagas.ts
> +    contribution: convertFromUlps(stats.contribution).toString(),
moved

2021-03-30 17:42 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/types.ts
> +  campaignDuration: number;
updated

2021-03-30 17:43 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/lib/AnalyticsApi.ts
> +        url: `${ETOS_PATH}/${etoId}/${STATS_PATH}`,
added

2021-03-30 18:04 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +                  {stats.equityTokensCreated} {equityTokenSymbol}
created, I called it `EquityToken` and didn't use any formatting as for this use case it's an integer. We can add that later

2021-03-30 18:07 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +                    separator: <>&nbsp;</>,
because it renders like this 
```
<span>
 <span data-test-id="value">0.3320</span></span> 
   EUR / token
 </span>
```
and sometimes that space is omitted

2021-03-30 18:11 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +                    eur: <Eth value={stats.equityTokenPriceAverage} noSymbol />,
cool that worked

2021-03-30 18:15 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +          <div className={styles.timeframeStats}>
good idea, updated

2021-03-30 18:19 UTC, arjunu commented on packages/shared-modules/src/modules/analytics/sagas.ts
> +  const stats = yield* call([analyticsApiService, "getEtoStats"], etoId);
added try catch

2021-03-30 18:31 UTC, arjunu commented on packages/shared-utils/src/utils/fileUtils.ts
> +export const createCsvDataUri = (dataAsString: string) =>
you are right, I didn't think about wallet :P Reverted.

2021-03-30 18:38 UTC, arjunu commented on packages/design-system/src/components/formatters/EquityToken.tsx
> +);
no formatting for now as we only need it to show integers

2021-03-30 18:52 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
>    React.useEffect(() => {
ok `onEnter` is better

2021-03-30 18:53 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +  if (!stats) {
I couldn't branch before because I needed undefined stats to check and dispatch action. Now that I used `onEnter` I moved this to branch

2021-04-01 07:42 UTC, desfero requested changes

2021-04-01 07:42 UTC, desfero commented on packages/shared-modules/src/modules/eto-analytics/module.ts
> +const MODULE_ID = generateSharedModuleId("analytics");
```suggestion
const MODULE_ID = generateSharedModuleId("eto-analytics");
```

2021-04-01 07:42 UTC, desfero commented on packages/shared-modules/src/modules/eto-analytics/reducer.ts
> +      return {
why do we reset the whole state here? We should only cleanup analytics for a given eto

2021-04-01 07:42 UTC, desfero commented on packages/shared-modules/src/modules/eto-analytics/sagas.ts
> +    logger.error(e, "Error while eto fundraising stats");
what will happen on UI? Do the user see the loading screen always?

2021-04-01 07:42 UTC, desfero commented on packages/shared-modules/src/modules/eto-analytics/selectors.ts
> +  selectEtoAnalyticsState(state).stats[etoId];
let's use `reselect`

2021-04-01 07:42 UTC, desfero commented on packages/shared-modules/src/modules/eto-analytics/types.ts
> +//   {
maybe a comment is not needed?

2021-04-01 08:56 UTC, arjunu commented on packages/shared-modules/src/modules/eto-analytics/module.ts
> +const MODULE_ID = generateSharedModuleId("analytics");
ooh nice catch

2021-04-01 08:58 UTC, arjunu commented on packages/shared-modules/src/modules/eto-analytics/types.ts
> +//   {
oops removed

2021-04-01 08:59 UTC, arjunu commented on packages/shared-modules/src/modules/eto-analytics/reducer.ts
> +      return {
leftover, removed

2021-04-01 14:21 UTC, desfero approved these changes

2021-04-01 15:27 UTC, merged