Arjunu/fundraising graph
Neufund/platform-frontend pull request #4823
Opened 2021-03-18 09:04 UTC by arjunu

2021-03-25 08:54 UTC, andywalton commented
@arjunu -> my only feedback here is that the graph always shows 1 single bar - I imagine this is due to the test data?

2021-04-06 11:35 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +          const dateSplit = date.replaceAll(",", "").split(" ");
https://caniuse.com/?search=replaceAll is relatively new but supported in all browsers

2021-04-06 11:35 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +          if (!date) {
this will never be undefined from our side but it is from GraphJS types

2021-04-06 11:37 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +            etoId === "0xa1c9b16bdCc0D5616a1C081914c87d98bD363674"
will remove this after @andywalton 's review

2021-04-07 08:35 UTC, desfero requested changes

2021-04-07 08:35 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +                  amount: value / 1000,
i would say we should use `formatShortNumber` util, showing `K` is too limited IMO

2021-04-07 08:35 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +          return intl.formatIntlMessage(
IMO we should use `formattedDate` and use appropriate date formatting for the given local we use right now

2021-04-07 08:35 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +              return intl.formatIntlMessage(
Same here, we should use `formatDate` from `intl`

2021-04-07 08:35 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +        <div className={styles.graphTitle}>Funds raised over time</div>
Why not `DashboardHeading`? And translation is missing

2021-04-07 08:35 UTC, desfero commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +const BreakdownGraphLayout: React.FunctionComponent<TProps & IIntlProps> = ({ data, intl }) => {
Let's add that to the `storybook` with `GREYP_DATA` as an example

2021-04-07 14:46 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +        title: function (context): string {
converted

2021-04-07 14:49 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +          if (!date) {
Used `invariant`

2021-04-07 16:16 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +          return intl.formatIntlMessage(
Had forgotten about `formatDate` function, updated

2021-04-07 16:32 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +                  amount: value / 1000,
Used `formatCurrency`

2021-04-07 16:32 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +              return intl.formatIntlMessage(
updated

2021-04-07 16:36 UTC, arjunu commented on packages/shared-modules/src/modules/eto-analytics/types.ts
> +}).defined();
without `defined` the object can be undefined. Or we have to use `.required`

2021-04-07 16:39 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +        <div className={styles.graphTitle}>Funds raised over time</div>
because it's the card title. Used FormattedMessage

2021-04-07 16:47 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +const BreakdownGraphLayout: React.FunctionComponent<TProps & IIntlProps> = ({ data, intl }) => {
added

2021-04-08 12:36 UTC, arjunu commented on packages/shared-modules/src/modules/eto-analytics/types.ts
> +const TEtoContributionGraphDataSchema = Yup.lazy(data =>
Added ticket for this https://github.com/Neufund/platform-frontend/issues/4851

2021-04-08 13:08 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.tsx
> +export const BreakdownGraph = compose<IIntlProps & TProps, TProps>(injectIntlHelpers)(
done

2021-04-08 13:54 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
> +            etoId === "0xa1c9b16bdCc0D5616a1C081914c87d98bD363674"
removed

2021-04-09 06:56 UTC, desfero requested changes
One small change to the story name

2021-04-09 13:45 UTC, arjunu commented on packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/BreakdownGraph.stories.tsx
> +storiesOf("ETO/Stats", module).add("BreakdownGraphLayout", () => <Component data={graphData} />);
updated

2021-04-10 14:01 UTC, desfero approved these changes

2021-04-11 16:26 UTC, merged