Auto unlock wallet app
Neufund/platform-frontend pull request #4835
Opened 2021-03-29 16:33 UTC by arjunu

2021-03-30 12:29 UTC, arjunu commented on packages/wallet/app/App.tsx
> +      initStatus === EInitStatus.IN_PROGRESS
there is still sometimes a white screen because of the delay between app opening and this code executing.

2021-03-30 13:07 UTC, arjunu commented on packages/wallet/app/App.tsx
> +      initStatus === EInitStatus.IN_PROGRESS
ok I updated `react-native-bootsplash` and the white screen seems to be gone now

2021-03-30 13:24 UTC, arjunu commented on packages/wallet/app/App.tsx
> +        // eslint-disable-next-line @typescript-eslint/no-floating-promises
because now `show` and `hide` return promises

2021-04-01 05:56 UTC, desfero commented on packages/wallet/app/App.tsx
> +      reset();
cool

2021-04-01 07:29 UTC, desfero requested changes
Some small comments

2021-04-01 07:29 UTC, desfero commented on packages/wallet/app/modules/auth/sagas.ts
> +import { EWalletExistenceStatus, walletEthModuleApi } from "modules/eth/module";
hm, i'm curious why it sorted that now and not before?

2021-04-01 07:29 UTC, desfero commented on packages/wallet/app/modules/auth/sagas.ts
> +      yield put(authActions.unlockAccount());
let's add a comment why we have both `yield* call(allowToUnlockExistingAccount);` and `yield put(authActions.unlockAccount());` as i was not sure initially why that was needed

2021-04-01 07:29 UTC, desfero commented on packages/wallet/storybook/index.tsx
>        RNBootSplash.hide();
let's also use `async/await` here

2021-04-01 10:43 UTC, arjunu commented on packages/wallet/storybook/index.tsx
>        RNBootSplash.hide();
done

2021-04-01 10:43 UTC, arjunu commented on packages/wallet/app/modules/auth/sagas.ts
> +import { EWalletExistenceStatus, walletEthModuleApi } from "modules/eth/module";
strange indeed

2021-04-01 10:43 UTC, arjunu commented on packages/wallet/app/App.tsx
> +        // eslint-disable-next-line @typescript-eslint/no-floating-promises
done

2021-04-01 10:45 UTC, arjunu commented on packages/wallet/app/modules/auth/sagas.ts
> +      yield put(authActions.unlockAccount());
done

2021-04-02 08:19 UTC, desfero approved these changes

2021-04-02 09:23 UTC, merged