Wallet connect wallet e2e
Neufund/platform-frontend pull request #4844
Opened 2021-04-06 18:41 UTC by arjunu

2021-04-07 10:08 UTC, arjunu commented on packages/wallet-e2e/tests/specs/assertUtils.specUtils.ts
> +export const assertLogout = () => {
thought of using this, but it is unused now. Didn't remove in case we wanna use it in future

2021-04-07 10:53 UTC, arjunu commented on packages/wallet-e2e/tests/specs/wallet-connect/disconnect.e2e.spec.ts
> +    browser.waitUntil(() => disconnected, {
A bit stupid but it's simple and works reliably. Easy to read code also. Webdriver polls until this condition is true or until timeout

2021-04-07 10:53 UTC, arjunu commented on packages/wallet-e2e/tests/specs/wallet-connect/killSession.e2e.spec.ts
> +    browser.call(() => connector.killSession());
`browser.call` waits for promise to resolve

2021-04-13 07:43 UTC, KonradFilipiak submitted a review, later dismissed

2021-04-14 06:58 UTC, desfero requested changes
Can we also assert 

1. Allert that appears after session was disconnected from the user side (web app side)
2. Wallet-connect modal changes in the wallet app (profile page)

2021-04-14 06:58 UTC, desfero commented on packages/wallet-e2e/tests/specs/wallet-connect/walletConnectAssertUtils.specUtils.ts
> +  return connector;
not sure we have to return connector and then overwrite it inside each test given it has not changed as it's a singleton instance. What do you think?

2021-04-14 06:58 UTC, desfero commented on packages/wallet-e2e/tests/specs/wallet-connect/killSession.e2e.spec.ts
> +    connector = assertSignMessage(connector);
I would also hide these two under one call given in the future we have to refactor wallet-connect implementation to show modal just once

2021-04-14 06:58 UTC, desfero commented on packages/wallet-e2e/tests/specs/wallet-connect/transaction.e2e.spec.ts
> +        txApproved = false;
do we need that catch here? There is no way from the code above for `txApprove` to be `true`

2021-04-14 09:05 UTC, arjunu commented on packages/wallet-e2e/tests/specs/wallet-connect/transaction.e2e.spec.ts
> +        txApproved = false;
eslint/typescript was complaining :D

2021-04-14 09:10 UTC, arjunu commented on packages/wallet-e2e/tests/specs/wallet-connect/transaction.e2e.spec.ts
> +        txApproved = false;
Removed and suppressed the error

2021-04-14 09:27 UTC, arjunu commented on packages/wallet-e2e/tests/specs/wallet-connect/killSession.e2e.spec.ts
> +    connector = assertSignMessage(connector);
combined

2021-04-14 09:29 UTC, arjunu commented on packages/wallet-e2e/tests/specs/wallet-connect/walletConnectAssertUtils.specUtils.ts
> +  return connector;
ok now it looks like this

``` 
const assertWCConnection = () => assertSignMessage(assertConnectionApprove());

// test code
const connector = assertWCConnection();
```

2021-04-14 13:33 UTC, desfero approved these changes

2021-04-14 14:16 UTC, merged