Fix keyboard avoiding view
Neufund/platform-frontend pull request #4853
Opened 2021-04-10 15:14 UTC by arjunu

Fixes https://github.com/Neufund/platform-frontend/issues/4722 and https://github.com/Neufund/platform-frontend/issues/4718

2021-04-13 10:56 UTC, desfero requested changes
Some changes request on slack

2021-04-21 07:50 UTC, desfero commented on packages/wallet/app/components/shared/Screen.tsx
> +  headerHeight + (isIOS ? insetBottom + spacingStyles.p4.padding : spacingStyles.p4.padding * 2);
not sure about the math here but from what i see.
if stack `mode` is `modal` then we calculate `keyboardVerticalOffset` with `headerHeight + (isIOS ? insetTop + 6 : 0)`
if stack mode is normal we just use `headerHeight` as an inset (i have no idea how to get `mode` type from `react-navigation` so for now we can support `modal` mode with some comment

2021-04-21 07:53 UTC, desfero commented on packages/wallet/app/components/shared/Screen.tsx
> +  headerHeight + (isIOS ? insetBottom + spacingStyles.p4.padding : spacingStyles.p4.padding * 2);
![image](https://user-images.githubusercontent.com/7031578/115517384-60029a00-a287-11eb-8966-f5722d444b8a.png)

2021-04-21 07:58 UTC, desfero commented on packages/wallet/app/components/shared/Screen.tsx
> +  headerHeight + (isIOS ? insetBottom + spacingStyles.p4.padding : spacingStyles.p4.padding * 2);
and 6 px is for that space in between inset and header

2021-04-21 08:03 UTC, desfero requested changes

2021-04-21 08:03 UTC, desfero commented on packages/wallet/app/components/shared/Screen.tsx
> +    const unsubscribeFocus = navigation.addListener("focus", () => {
Wny not `https://reactnavigation.org/docs/use-focus-effect` effect?

2021-04-21 08:03 UTC, desfero commented on packages/wallet/app/components/shared/Screen.tsx
> +    <Animated.ScrollView
to not duplicate this can be kept as a variable

2021-04-21 08:03 UTC, desfero commented on packages/wallet/app/components/shared/Screen.tsx
> +  return keyboardAvoidingViewEnabled ? (
we need to duplicate the same in normal `Screen` component, right?

2021-04-21 09:40 UTC, arjunu commented on packages/wallet/app/components/shared/Screen.tsx
> +    <Animated.ScrollView
done

2021-04-21 09:44 UTC, arjunu commented on packages/wallet/app/components/shared/Screen.tsx
> +  return keyboardAvoidingViewEnabled ? (
yes but I can't test it since we don't have a screen that uses `SafeAreaScreen` and inputs. Ok I will add a TODO

2021-04-21 13:58 UTC, arjunu commented on packages/wallet/app/components/shared/Screen.tsx
> +    const unsubscribeFocus = navigation.addListener("focus", () => {
didn't know about it, used it

2021-04-21 14:44 UTC, arjunu commented on packages/wallet/app/components/shared/Screen.tsx
> +  headerHeight + (isIOS ? insetBottom + spacingStyles.p4.padding : spacingStyles.p4.padding * 2);
updated

2021-04-22 09:07 UTC, desfero approved these changes

2021-04-26 07:56 UTC, merged