Fix tab switch crash
Neufund/platform-frontend pull request #4863
Opened 2021-04-13 15:54 UTC by arjunu

2021-04-13 15:56 UTC, arjunu commented on packages/wallet/app/components/screens/HomeScreen/HomeScreen.tsx
> +    onFocus: (dispatch, { screenState }) =>
this fixes a crash when you switch tab while it is still loading and when you come back on Focus the `screenState` would be  `EScreenState.REFRESHING` and selector will crash

2021-04-13 15:57 UTC, arjunu commented on packages/wallet/app/components/screens/HomeScreen/HomeScreen.tsx
> +    onMount: (dispatch, { screenState }) =>
this changes showing skeleton animation every time we switch tabs, the data is already in the reducer so it is a bit annoying to see skeleton

2021-04-19 09:10 UTC, desfero requested changes
Discussed on slack, we will fix that on sagas level without doing `if`s in components

2021-04-22 09:42 UTC, desfero approved these changes

2021-04-23 11:21 UTC, KonradFilipiak approved these changes

2021-04-23 11:25 UTC, merged