Exit claim
Neufund/platform-frontend pull request #4873
Opened 2021-04-17 14:09 UTC by arjunu

2021-04-22 19:28 UTC, arjunu commented on packages/shared-modules/src/modules/contracts/lib/IERC223Token.ts
> +interface IERC223Token {
is there a better way to do this? See `packages/wallet/app/modules/contracts/lib/ContractsService.ts`, I had to force cast the implementation method because I couldn't add a factory for this in wallet

2021-04-22 19:29 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.tsx
> +  const done = txTimestamp && txTimestamp > 0;
because this component is shared by both summary and success modals

2021-04-22 19:30 UTC, arjunu commented on packages/web/app/config/configUtils.ts
> -export function getRequiredEnv(env: unknown, name: string): string {
moved to `packages/web/app/config/getConfig.ts`

2021-04-23 11:15 UTC, andywalton commented
<img width="667" alt="Screenshot 2021-04-23 at 13 08 51" src="https://user-images.githubusercontent.com/609657/115863529-de9d3a00-a435-11eb-9476-adcb44d38981.png">

Please will you change the text `Total payout due to you` to `Your total payout`

2021-04-23 11:19 UTC, andywalton commented
Hi @arjunu 

If a payout is unsuccessful, please will you change the tense of the `Amount sent` label to rather read `Amount to send` as we haven't actually sent any tokens because it failed.

Ultimately we should improve these but until we revamp this flow please for this case will you update the label. For the payout success is makes sense to say `Amount sent` as it actually happened.

<img width="1440" alt="Screenshot 2021-04-23 at 13 10 33" src="https://user-images.githubusercontent.com/609657/115863690-1ad09a80-a436-11eb-9e14-b2a9747d7474.png">

2021-04-23 12:15 UTC, andywalton commented
Hi again @arjunu -> Thanks I retried and I could successfully complete the payout transaction. 🥇 That transactions also show up in my Wallet.

The only thing I noticed was that upon completion I could still see the asset in the Portfolio view under `Your assets` section. Ie. here:

<img width="1440" alt="Screenshot 2021-04-23 at 14 02 14" src="https://user-images.githubusercontent.com/609657/115869399-1f994c80-a43e-11eb-85a6-0f79332aa4cd.png">

The view didn't move the asset to `Past investments` and the `Claim payout` button was still enabled. Which when clicked just shows a Transaction failure modal.

<img width="1440" alt="Screenshot 2021-04-23 at 14 02 31" src="https://user-images.githubusercontent.com/609657/115869487-3a6bc100-a43e-11eb-9cae-9cab23dc1d12.png">

I think we need to handle this state change better?

2021-04-26 09:33 UTC, arjunu commented on packages/web/scripts/get-shas-from-health-check.js
> +        Authorization: "Basic " + env.NEUFUND_HEALTH_API_TOKEN,
Just realised I forgot `NF_`

2021-04-28 07:14 UTC, desfero commented on packages/design-system/src/components/error/ErrorMessage.module.scss
> +  padding: px-to-rem(8px);
let's always use `$spacings` styles everywhere like we do in mobile app

2021-04-28 07:14 UTC, desfero commented on packages/design-system/src/components/error/ErrorMessage.tsx
> +    <InlineIcon className={styles.icon} width="16px" height="14px" alt="" svgIcon={errorIcon} />
width and height can come from styles, right?

2021-04-28 07:15 UTC, desfero commented on packages/design-system/src/components/error/ErrorMessage.tsx
> +  className?: string;
let's just add `CommonHtmlProps` to not specify `className` manually. In long term we can rename that to `TClassName` for consistency with `TDataTestId`

2021-04-28 07:16 UTC, desfero commented on packages/design-system/src/components/error/ErrorMessage.tsx
> +  <div className={cn(styles.wrapper, className)}>
i would say it can be `p`?

2021-04-28 07:17 UTC, desfero commented on packages/design-system/src/components/error/ErrorMessage.tsx
> +  <div className={cn(styles.wrapper, className)}>
Do we also need to aria attributes for better accessibility? Like role, aria-live, aria-errormessage?

2021-04-28 11:17 UTC, desfero requested changes

2021-04-28 11:17 UTC, desfero commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutSummary.tsx
> +            <span>
hm, do we need `span`?

2021-04-28 11:17 UTC, desfero commented on packages/wallet/app/modules/contracts/lib/ContractsService.ts
> +      return Promise.resolve(this.exitControllerCache[equityTokenAddress]);
Do you need to `Promise.resolve`?

2021-04-28 11:17 UTC, desfero commented on packages/shared-modules/src/modules/contracts/lib/IERC223Token.ts
> +interface IERC223Token {
And what's the problem that you can't add a factory?

2021-04-28 12:21 UTC, arjunu commented on packages/design-system/src/components/error/ErrorMessage.module.scss
> +  padding: px-to-rem(8px);
updated

2021-04-28 12:22 UTC, arjunu commented on packages/design-system/src/components/error/ErrorMessage.tsx
> +import cn from "classnames";
different design

2021-04-28 12:23 UTC, arjunu commented on packages/design-system/src/components/error/ErrorMessage.tsx
> +  className?: string;
updated

2021-04-28 13:01 UTC, arjunu commented on packages/design-system/src/components/error/ErrorMessage.tsx
> +  <div className={cn(styles.wrapper, className)}>
Added `role`, I think we don't need `aria-errormessage` since the error in inside this

2021-04-28 13:03 UTC, arjunu commented on packages/design-system/src/components/error/ErrorMessage.tsx
> +    <InlineIcon className={styles.icon} width="16px" height="14px" alt="" svgIcon={errorIcon} />
updated

2021-04-28 13:05 UTC, arjunu commented on packages/design-system/src/components/formatters/EquityToken.tsx
> +    formatCurrency({
added memo while exporting

2021-04-28 13:25 UTC, arjunu commented on packages/shared-modules/src/modules/eto/sagas.ts
> +  const exitController = yield* call([contractsService, "getExitController"], equityTokenAddress);
updated

2021-04-28 13:45 UTC, arjunu commented on packages/shared-modules/src/modules/eto/types.ts
> +  "SETUP" = "0",
because the value coming from control is BigNumber so I have to do `toNumber` :P

2021-04-28 13:46 UTC, arjunu commented on packages/wallet/.env.template
> +NF_EXIT_CONTROLLER_ADDRESSES="0xf0e27758f63fd0d7af8538cac54afd701ab57c4d:0x7F845CBaF2a723Ca40189e9D49df5bC242Dc260a"
nope

2021-04-28 13:49 UTC, arjunu commented on packages/wallet/app/modules/contracts/lib/ContractsService.ts
> +      return Promise.resolve(this.exitControllerCache[equityTokenAddress]);
it was used in `getETOCommitmentContract` above, will remove and see

2021-04-28 13:51 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/TxSender/TxSender.stories.tsx
> +storiesOf("TxSenderModal, walletConnect EXIT_CLAIM", module)
updated

2021-04-28 14:11 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/TxSender/TxSender.stories.tsx
> +storiesOf("TxSenderModal, walletConnect EXIT_CLAIM", module)
ok I combined all of them except for exit claim because it needs different store state for done and error cases

2021-04-28 14:12 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.module.scss
> +  padding: px-to-rem(16px) 0;
updated

2021-04-28 14:13 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.module.scss
> +  flex-flow: column;
updated

2021-04-28 14:16 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.module.scss
> +  font-weight: normal;
because I had given bold for the whole row, removed

2021-04-28 14:18 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutSummary.tsx
> +            <span>
leftover, removed

2021-04-28 14:30 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.tsx
> +  const done = txTimestamp && txTimestamp > 0;
removed

2021-04-29 11:20 UTC, arjunu commented on packages/shared-modules/src/modules/contracts/lib/IERC223Token.ts
> +interface IERC223Token {
leaving this as it is for now

2021-04-29 11:55 UTC, arjunu commented on packages/design-system/src/components/formatters/EquityToken.tsx
> +      valueType: ECurrency.ETH,
used opaque type Equity Token

2021-04-29 14:44 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.tsx
> +        <tr className={styles.borderBottom}>
Talked to @andywalton, we're gonna do refactoring

2021-04-29 14:45 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.tsx
> +            <Eth value={additionalData.gasCost} />
`validateGas` handles it, so if stipend is available we still show original gas value here but user won't get any errors

2021-04-29 14:45 UTC, arjunu commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.tsx
> +            <EurToken value={additionalData.payout} />
used Money for now, didn't refactor it. It's used in a lot of places, so we can do a separate ticket to make it like wallet's MoneyUnsafe

2021-05-01 07:33 UTC, desfero commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.tsx
> +            <Eth value={additionalData.gasCost} />
but what if we stipend the whole cost? We will show `zero` in that case which can be misleading for the user IMO. But anyway we can handle that later given it's the same for all other transactions

2021-05-01 07:33 UTC, desfero commented on packages/web/app/components/modals/tx-sender/exit-claim-flow/ExitClaimPayoutDetails.tsx
> +            <EurToken value={additionalData.payout} />
sure, we can do a ticket and refactor money later

2021-05-01 07:45 UTC, desfero requested changes

2021-05-01 07:45 UTC, desfero commented on packages/web/app/components/shared/MoneySuiteWidget/MoneySuiteWidget.tsx
> +  const bottom = useApproxSign ? (
👍

2021-05-01 07:45 UTC, desfero commented on packages/web/app/modules/tx/transactions/exit-claim/sagas.ts
> +  const contractInstance = yield* call(async () => await contractsService.getERC223(tokenAddress));
i think the proper way would be to call it like `yield* call([contractService, "getERC223"], tokenAdress)` as then we can mock `getERC223` call later in tests

2021-05-01 07:45 UTC, desfero commented on packages/web/app/modules/tx/transactions/exit-claim/sagas.ts
> +  const gasPriceWithOverhead = yield* select(selectCurrentGasPriceWithOverHead);
would be move to select gas price part above `invariant` call on the next line for better readability

2021-05-01 07:45 UTC, desfero commented on packages/web/app/modules/tx/transactions/exit-claim/sagas.ts
> +    web3Manager.estimateGasWithOverhead(txInitialDetails),
same here as with `getERC223` method call

2021-05-01 07:45 UTC, desfero commented on packages/web/app/modules/tx/transactions/exit-claim/sagas.ts
> +    logger.info("Exit claim cancelled" + e);
`logger.error` would be better IMO. In case of cacnel we should refactor `txSendSaga` laster to not throw any error in case of cancel but just cleanup the store

2021-05-01 07:46 UTC, desfero submitted a review, later dismissed

2021-05-03 09:48 UTC, arjunu commented on packages/web/app/modules/tx/transactions/exit-claim/sagas.ts
> +    web3Manager.estimateGasWithOverhead(txInitialDetails),
updated

2021-05-03 09:48 UTC, arjunu commented on packages/web/app/modules/tx/transactions/exit-claim/sagas.ts
> +  const contractInstance = yield* call(async () => await contractsService.getERC223(tokenAddress));
updated

2021-05-03 09:48 UTC, arjunu commented on packages/web/app/modules/tx/transactions/exit-claim/sagas.ts
> +    logger.info("Exit claim cancelled" + e);
updated

2021-05-03 11:00 UTC, desfero approved these changes

2021-05-04 16:58 UTC, ozanmanav-ng approved these changes

2021-05-12 10:53 UTC, KonradFilipiak approved these changes

2021-05-12 13:39 UTC, desfero approved these changes

2021-05-12 13:39 UTC, merged