#4891 Monitor TX migration
Neufund/platform-frontend pull request #4899
Opened 2021-04-23 14:55 UTC by desfero

2021-04-28 09:18 UTC, desfero commented on packages/shared-modules/src/modules/eto/sagas.spec.ts
> +    throw new Error("Not implemented");
Should be done as a part of #4414

2021-04-28 09:20 UTC, desfero commented on packages/shared-modules/src/modules/tx/monitor/sagas.ts
> +    // yield take(actions.web3.newBlockArrived);
will do a separate issue to add block tracker to `shared-modules`

2021-04-30 18:03 UTC, arjunu requested changes
one comment

2021-04-30 18:03 UTC, arjunu commented on packages/shared-modules/src/modules/tx/monitor/sagas.ts
> +  yield* takeLatestUntil(authModuleAPI.actions.setUser, authModuleAPI.actions.reset, txMonitor);
move to web app init module

2021-05-04 14:28 UTC, ozanmanav-ng commented on packages/shared-modules/src/modules/tx/core/sagas/getTransactionOrThrow.ts
> +import { neuGetBindings } from "../../../../utils";
Shouldn't we use alias for this ?

2021-05-05 07:20 UTC, desfero commented on packages/shared-modules/src/modules/tx/core/sagas/getTransactionOrThrow.ts
> +import { neuGetBindings } from "../../../../utils";
good point, unfortunately we don't have yet setup for aliases in `shared-modules`

2021-05-05 13:28 UTC, desfero commented on packages/shared-modules/src/modules/tx/monitor/sagas.ts
> +  yield* takeLatestUntil(authModuleAPI.actions.setUser, authModuleAPI.actions.reset, txMonitor);
done

2021-05-05 13:32 UTC, arjunu approved these changes

2021-05-05 16:52 UTC, merged