Ozan/4882 update landing views to latest designs
Neufund/platform-frontend pull request #4900
Opened 2021-04-23 19:18 UTC by ozanmanav-ng

2 new libraries have been added in this PR.

1- react-native-snap-carousel (for Carousel and Effects)
2- react-native-responsive-dimensions (responsive height-width)
3- react-native-sensors (gyroscope sensor for animation image)

2021-04-29 07:56 UTC, desfero commented on packages/wallet/app/components/screens/LandingScreen/LandingCarousel.tsx
> +const LandingCarousel = pure(LandingCarouselBase);
Given that `LandingCarouselBase` is a function component that we own maybe we should use `React.memo` 
https://github.com/facebook/react/blob/0e100ed00fb52cfd107db1d1081ef18fe4b9167f/packages/react/src/ReactMemo.js

From the code i see that it does not create a new component but rather add some metadata to existing

2021-04-29 10:31 UTC, desfero requested changes

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/screens/LandingScreen/LandingCarouselEntry.tsx
> +  subTitle: { ...typographyStyles.body, textAlign: "center", color: grayLighter2 },
`typographyStyles` should be used in rare cases given we have more specialized components like `BodyText` or `Headline` (same with `title` above)

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/screens/LandingScreen/LandingCarouselEntry.tsx
> +const LandingCarouselEntry = pure(LandingCarouselEntryBase);
Same applies i think to all uses of `pure` in the PR as it's always done for functional components

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/screens/LandingScreen/LandingCarouselPagination.tsx
> +    paddingVertical: 8,
we should use `spacingsStyles` for all math around padding/margings/borders. For eh `marginHorizontal: 5` is invalid given it's not based on 4 (4,8,16,20 etc)

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/screens/LandingScreen/LandingScreen.tsx
> +          {Config.NF_CONTRACT_ARTIFACTS_VERSION === "localhost" && (
The whole landing pagination should not be based on position: absolute but rather use `flex-grow` to allow some containers to shrink. Try to add two more buttons here and you will see how the layout is broken given it's positioned absolutely.

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/screens/LandingScreen/carouselEntries.ts
> +    subTitle: "Set up a new or use your existing account to get going.",
Can you put all these to `en-en.json` translations?

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/screens/LandingScreen/carouselEntries.ts
> +    id: 0,
id can be generated from array index? We can also use some `string` as id's like `welcome`, `connect`, `transactions`, etc. Up to you

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/screens/LandingScreen/carouselEntries.ts
> +  featureIllustration?: EIllustrationType;
always defined in `CAROUSEL_ENTRIES`? So we optional?

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/shared/GyroscopeAnimator.tsx
> +  }, [translate, enabled]);
do we need `translate` ? I'm not sure react will track that given it's a ref value

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/shared/GyroscopeAnimator.tsx
> +      setUpdateIntervalForType(SensorTypes.gyroscope, UPDATE_INTERVAL);
hm, no need to set that on a component level IMO. We can push that to some `gyroscope` config file given `UPDATE_INTERVAL` is a static constant

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/shared/GyroscopeAnimator.tsx
> +        try {
do we need `try` catch here?

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/shared/GyroscopeAnimator.tsx
> +        () => {
do we need that empty function?

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/shared/GyroscopeAnimator.tsx
> +      const last_x = [0],
let's use camelCase for normal variables. Strange that we don't have lint rule for that

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/shared/Illustration.stories.tsx
> +        <View style={{ flex: 1, backgroundColor: "#94a5b3" }} key={`${type}-${index}`}>
let's use backgroundColor from color for consistency

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/shared/Illustration.tsx
> +import Landing1 from "assets/illustrations/illustration_landing_1.svg";
let's use `-` as a separator to have consistency with other assets names

2021-04-29 10:31 UTC, desfero commented on packages/wallet/app/components/shared/buttons/Button.tsx
> +    borderRadius: 24,
For that we have a separate ticket for both web and wallet

2021-04-29 11:25 UTC, ozanmanav-ng commented on packages/wallet/app/components/screens/LandingScreen/LandingCarousel.tsx
> +      removeClippedSubviews={!isIOS}
They are suggesting for optimize performance android. I'm adding as comment.

https://github.com/meliorence/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#optimizing-performance

2021-04-29 12:13 UTC, ozanmanav-ng commented on packages/wallet/app/components/shared/buttons/Button.tsx
> +    borderRadius: 24,
ok reverted

2021-04-29 12:32 UTC, ozanmanav-ng commented on packages/wallet/app/components/shared/GyroscopeAnimator.tsx
> +  }, [translate, enabled]);
eslint it expecting it 
![image](https://user-images.githubusercontent.com/82657734/116550962-0b52c500-a900-11eb-954c-00a6d37ec2aa.png)

2021-04-29 12:48 UTC, ozanmanav-ng commented on packages/wallet/app/components/shared/GyroscopeAnimator.tsx
> +      setUpdateIntervalForType(SensorTypes.gyroscope, UPDATE_INTERVAL);
moved to config.ts with gyroscope-animator folder

2021-04-29 13:18 UTC, ozanmanav-ng commented on packages/wallet/app/components/screens/LandingScreen/LandingScreen.tsx
> +          {Config.NF_CONTRACT_ARTIFACTS_VERSION === "localhost" && (
There is a limitations because of the landing screen background. Background should  be everytime in the background. If i use flex, it is spacing and moving to top.

2021-04-29 14:39 UTC, desfero requested changes

2021-04-29 14:39 UTC, desfero commented on packages/wallet/app/components/shared/gyroscope-animator/GyroscopeAnimator.tsx
>        const last_x = [0],
can we use `camelCase` here?

2021-04-29 14:39 UTC, desfero commented on packages/wallet/app/components/shared/gyroscope-animator/GyroscopeAnimator.tsx
> +    subscribeGyroscope();
now we will never unsubscribe from the listener given the callback for unsubscription flow is never returned

2021-04-29 14:44 UTC, ozanmanav-ng commented on packages/wallet/app/components/shared/gyroscope-animator/GyroscopeAnimator.tsx
> +    subscribeGyroscope();
But I'm doing unsubscribe at line 51. If it entered the subscribe, it will be unsubscribe.

2021-04-30 08:56 UTC, desfero approved these changes

2021-04-30 08:57 UTC, merged