#4715 Implement push notifications support for wallet connect
Neufund/platform-frontend pull request #4901
Opened 2021-04-26 07:24 UTC by desfero

2021-04-26 17:58 UTC, desfero commented on packages/wallet/app/modules/auth/sagas.spec.ts
> +        .silentRun();
given these are infinite sagas

2021-04-26 19:26 UTC, ozanmanav-ng submitted a review, later dismissed
LGTM

2021-04-27 10:40 UTC, arjunu requested changes
two things to check
- accepting alert
![image](https://user-images.githubusercontent.com/4038217/116228516-ad827980-a755-11eb-8d94-ff178e034558.png)
- if session is cleared between tests in wallet connection session suite (and to fix the failure)
https://app-automate.browserstack.com/dashboard/v2/builds/f6e7c97a2801f18910fee63f8cda2945c95e5798/sessions/5d7634e1489ae26c5a37f7084debda1e59f04c21

2021-04-30 09:51 UTC, arjunu approved these changes

2021-05-06 08:12 UTC, KonradFilipiak approved these changes

2021-05-07 11:39 UTC, merged