Wallet transaction detail view
Neufund/platform-frontend pull request #4904
Opened 2021-04-26 12:39 UTC by Schabaani

2021-04-26 14:59 UTC, arjunu commented on packages/wallet/app/components/screens/WalletScreen/TransactionDetail/TransactionDetail.tsx
> +import { TTxHistory } from "@neufund/shared-modules";
let's call this `TransactionDetailScreen` and move to `screens/TransactionDetailScreen`

2021-04-26 15:05 UTC, arjunu commented on packages/wallet/app/components/screens/WalletScreen/TransactionDetail/RedistributePayoutTransactionsDetails.tsx
> +    <TransactionDetailsHeader
what about `ModalStackHeader`?

2021-04-26 15:23 UTC, arjunu commented on packages/wallet/app/components/shared/money-suite-widget/MoneySuiteWidget.tsx
> +          ≈ <MoneyUnsafe token={analogToken} color={"red"} />
I think this value is always Euro so we can use `<Eur/>`

2021-04-26 15:26 UTC, arjunu commented on packages/wallet/app/components/screens/WalletScreen/TransactionDetail/TransferTransactionDetails.tsx
> +    bigTitle = formattedValue(transaction, transaction.amountEur) + unit;
these two can be `MoneyUnsafe`

2021-04-28 10:12 UTC, arjunu commented on packages/wallet/app/router/WalletStack.tsx
> +      <WalletStack.Screen
![image](https://user-images.githubusercontent.com/4038217/116387018-a5d8d880-a81a-11eb-92dc-c769f49ae9cd.png)

The tabs shouldn't be visible in TransactionDetailScreen as per design

2021-04-28 10:13 UTC, arjunu commented on packages/wallet/app/router/WalletStack.tsx
> +function WalletStackScreen() {
this can be in `AppAuthRouter` no, why create a separate stack?

2021-04-28 10:18 UTC, arjunu commented on packages/wallet/app/router/WalletStack.tsx
> +function WalletStackScreen() {
Move these two to  `AppAuthRouter ` as `Stack.Screen`, we have all routes there

2021-04-28 10:20 UTC, arjunu commented on packages/wallet/app/components/shared/CopyToClipboardButton.tsx
> +import Clipboard from "@react-native-community/clipboard";
can you run `yarn` again? It will install pods. Somehow `RNCClipboard` is missing from `packages/wallet/ios/Podfile.lock`

2021-04-28 10:27 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/EtoInvestmentTransactionDetails.tsx
> +  bigTitle = <MoneyUnsafe token={token} />;
no need to use `let`, it can be `const smallTitle = <MoneyUnsafe token={token} />;`

And these lines can be part of `TransactionDetailsHeader`. Looks like they are duplicated for every transaction type

2021-04-28 10:28 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/EtoInvestmentTransactionDetails.tsx
> +      <TransactionDetailsHeader
`TransactionDetailsHeader` this can be moved to `TransactionDetailScreenLayout` if it is same for all transaction types

2021-04-28 10:29 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionTypeToComponentMap.tsx
> +export const TransactionContent: React.FunctionComponent<IExternalProps> = props => (
this component is unnecessary, it has only one child. `TransactionTypeToComponentMap` can be moved to `TransactionDetailScreenLayout`

2021-04-28 10:30 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionTypeToComponentMap.tsx
> +    {/* <EtherscanTxLink txHash={props.transaction.txHash}>Etherscan</EtherscanTxLink> */}
clean up commented code

2021-04-28 10:39 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +    ...typographyStyles.headline2,
it is 15 pixels in the design, can you use `typographyStyles.bodyBold` instead?

2021-04-28 10:42 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +  name: { ...typographyStyles.bodyBold, color: baseGray },
fontsize doesn't match design

2021-04-28 10:45 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +  smallTitle: {
the spacing between the lines doesn't match design, can you re-verify it
![image](https://user-images.githubusercontent.com/4038217/116391575-a2941b80-a81f-11eb-9531-83aa0a7155b6.png)
![image](https://user-images.githubusercontent.com/4038217/116391600-a9bb2980-a81f-11eb-9c68-dc1e99f6893a.png)

2021-04-28 10:47 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +        <TouchableOpacity
use `ButtonIcon`

2021-04-28 10:48 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +        <Text style={styles.name}>{transactionName}</Text>
there are some components in `components/typography` check if any of these match the pre defined styles, if they do you can use them

2021-04-28 10:48 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +const TransactionStatus: React.FunctionComponent<{
one line space between blocks of code please

2021-04-28 10:48 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +const styles = StyleSheet.create({
one line of space between blocks of code please

2021-04-28 10:50 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +const Container = ({ children }) => <View style={styles.container}>{children}</View>;
if this component is used for all transaction types, this `View` can be moved to `TransactionDetailScreenLayout`

2021-04-28 10:51 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionTypeToComponentMap.tsx
> +import { EtoInvestmentTransactionDetails } from "./EtoInvestmentTransactionDetails";
let's put all the transaction type components in a sub directory called transaction detail types or something like that

2021-04-28 10:54 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +const TransactionDetailsHeader: React.FunctionComponent<TTransactionHeaderProps> = ({
this component should be in it's own file since it is a sibling of `BasicTransactionDetails`

2021-04-28 10:56 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +    height: HEADER_HEIGHT,
this doesn't need height if you give correct padding and margin as per design

2021-04-28 10:58 UTC, arjunu commented on packages/wallet/app/components/shared/DataRow.tsx
> +const DataRow: React.FunctionComponent<IDataRowProps & TDataTestId> = ({
call this TransactionDetailRow or something and move it to TransactionDetailScreen directory, we don't know if we will reuse this. If we do then we can make it a common component later

2021-04-28 10:59 UTC, arjunu commented on packages/wallet/app/components/shared/DataRow.tsx
> +enum EDataRowSize {
this is not needed

2021-04-28 10:59 UTC, arjunu commented on packages/wallet/app/components/shared/DataRow.tsx
> +enum EDataRowSize {
you can remove all unused types and props, it doesn't have to be same as web.

2021-04-28 11:04 UTC, arjunu commented on packages/wallet/app/components/shared/DataRow.tsx
> +  margin: { ...spacingStyles.ml2 },
the spacing doesn't match design, the space between text and the edges is 20px. Give padding & margin such that each DataRow is of the same height

2021-04-28 11:04 UTC, arjunu commented on packages/wallet/app/components/shared/CopyToClipboardButton.tsx
> +  <TouchableOpacity style={{ ...style }} onPress={() => Clipboard.setString(value)}>
Use ButtonIcon, and the icon doesn't match design. You can ask @andywalton for the right icon svg

2021-04-28 11:07 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +      return assertNever(status, "Unsupported eto investment transaction subtype");
so what this statement means is that if there is a new `ETransactionStatus` then this switch case doesn't know how to handle it. So this message should say "Unsupported status" or something like that. I saw other `assertNever` statements, can you check and update them too?

2021-04-28 11:09 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +const Circle: React.FunctionComponent<{ color: string }> = ({ color }) => (
we always create a type and never directly write props like this

```
TCircleProps = {
  color: string;
}  

const Circle: React.FunctionComponent<TCircleProps> = ({ color }) => (}

2021-04-28 11:10 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +  date: any;
never use `any`

2021-04-28 11:12 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +          <FormattedDate
in the design the date has a hyphen, but this renders comma, can u check?

2021-04-28 11:12 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +          <FormattedDate
` 23 Feb 2021 - 09:19 UTC`

2021-04-28 11:16 UTC, arjunu commented on packages/wallet/app/components/shared/links/EtherscanLink.tsx
> +import {
can you remove unused props and types?

2021-04-28 11:25 UTC, arjunu commented on packages/wallet/app/components/shared/links/ExternalLink.tsx
> +  React.DetailedHTMLProps<React.AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>,
HTMLProps? Update it for React native link

2021-04-28 11:27 UTC, Schabaani commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionTypeToComponentMap.tsx
> +export const TransactionContent: React.FunctionComponent<IExternalProps> = props => (
I do this because of its switch-case.

2021-04-28 11:27 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/EtoInvestmentTransactionDetails.tsx
> +        )}
![image](https://user-images.githubusercontent.com/4038217/116396213-68c61380-a825-11eb-9b46-548abfc89f7b.png)
View on etherscan is missing for all types

2021-04-28 11:28 UTC, arjunu commented on packages/wallet/app/locales/en-en.json
> +  "wallet.transaction-detail.common.to-address.caption": "To Address",
no need for `.caption` suffix

2021-04-28 11:29 UTC, arjunu commented on packages/wallet/app/locales/en-en.json
> +  "wallet.transaction-detail.common.to-address.caption": "To Address",
```suggestion
  "wallet.transaction-detail.common.to-address.caption": "To address",
```

2021-04-28 11:29 UTC, arjunu commented on packages/wallet/app/locales/en-en.json
> +  "wallet.transaction-detail.common.from-address.caption": "From Address",
```suggestion
  "wallet.transaction-detail.common.from-address.caption": "From address",
```

2021-04-28 11:30 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/EtoInvestmentTransactionDetails.tsx
> +          value={<EtherscanAddressLink address={transaction.toAddress} />}
in the design to and from address doesn't look like links, can verify with @andywalton ?

2021-04-28 11:33 UTC, arjunu commented on packages/wallet/app/components/shared/money-suite-widget/MoneySuiteWidget.tsx
> +import { TTranslatedString } from "@neufund/shared-modules";
can you clean up this file to remove unused types and props? Keep only the things that are required for what you see in the mobile designs.

2021-04-28 11:38 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/EtoRefundTransactionsDetails.tsx
> +        <ExternalLink href={etoPublicViewByIdLinkLegacy(transaction.etoId)}>
this can be a shared component since it is used multiple times

2021-04-28 11:42 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +import { ETransactionStatus } from "@neufund/shared-modules";
add a story for this component

2021-04-28 11:47 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetailScreen.tsx
> +const TransactionDetailScreenLayout: React.FunctionComponent<
can u add stories with different transaction types? like this https://neufund.github.io/platform-frontend/@neufund/web/?path=/story/templates-transaciondetailsmodal--transfer-out-transaction

See the web story. It is taking data from fixtures

2021-04-28 11:59 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/NEurRedeemTransactionDetails.tsx
> +                <Money
remove FormatShortNumber, FormattNumber and Money.

use MoneyUnsafe or Eur.

2021-04-28 12:03 UTC, arjunu commented on packages/wallet/app/components/shared/money-suite-widget/utils.tsx
> +      return EIconType["N_EUR"];
```suggestion
      return EIconType.N_EUR;
```

2021-04-28 12:04 UTC, arjunu commented on packages/wallet/app/components/shared/money-suite-widget/utils.tsx
> +  switch (currency) {
there are icons missing for some token types, if you add stories for all tx types you can catch them

2021-04-28 12:06 UTC, arjunu submitted a review, later dismissed
few comments

2021-04-29 06:01 UTC, Schabaani commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +      return assertNever(status, "Unsupported eto investment transaction subtype");
I've copied it from web package, `TransactionStatus` component. Can I change that?

2021-04-29 06:13 UTC, Schabaani commented on packages/wallet/app/components/shared/money-suite-widget/utils.tsx
> +  switch (currency) {
copied from `design-system`, `CurrencyIcon.tsx` component. should I add more types there?

2021-04-29 09:16 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +      return assertNever(status, "Unsupported eto investment transaction subtype");
I just mean change the string `"Unsupported eto investment transaction subtype"`. `assertNever` throws error and this string is the error message. Someone forgot to update the string

2021-04-29 11:29 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionTypeToComponentMap.tsx
> +export const TransactionContent: React.FunctionComponent<IExternalProps> = props => (
I mean what about like this:
```
TransactionDetailScreenLayout = () => (
 <TransactionTypeToComponentMap/>
)

2021-05-15 19:13 UTC, arjunu commented on packages/wallet/app/assets/arrow-back.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
unused icon but I kept it in case we need for future

2021-05-15 19:17 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetail.tsx
> +  // Todo use TTranslatedString
I have added `TTranslatedString` in https://github.com/Neufund/platform-frontend/pull/4924 and it will be merged before this so update later

2021-05-15 21:36 UTC, arjunu commented on packages/wallet/patches/@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch
> +diff --git a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
will add patch notes in https://github.com/Neufund/platform-frontend/pull/4924

2021-05-15 21:36 UTC, arjunu commented on packages/wallet/patches/react-native-gesture-handler+1.5.6.patch
> -diff --git a/node_modules/react-native-gesture-handler/react-native-gesture-handler.d.ts b/node_modules/react-native-gesture-handler/react-native-gesture-handler.d.ts
we don't need this anymore

2021-05-16 15:19 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetailsHeader.tsx
> +    maxWidth: 200,
will replace this with `responsiveScreenWidth` from `react-native-responsive-dimensions` once https://github.com/Neufund/platform-frontend/pull/4924/files is merged

2021-05-17 08:02 UTC, arjunu commented on packages/wallet/app/modules/wallet-screen/module.ts
> +  // TODO ask Pawel why these are re exported?
@desfero ?

2021-05-19 08:41 UTC, desfero requested changes
a couple of comments

2021-05-19 08:41 UTC, desfero commented on packages/wallet/app/components/shared/CopyToClipboardButton.tsx
> +    accessibilityHint="Copy"
I'm wondering how that would be read by a screen reader? Maybe we can avoid duplication?

2021-05-19 08:41 UTC, desfero commented on packages/wallet/app/components/shared/formatters/MoneySuite.stories.tsx
> +  <View>
cool can we move that to some storybook shared utils?

2021-05-19 08:41 UTC, desfero commented on packages/wallet/app/components/shared/formatters/MoneySuite.tsx
> +          ≈ <Eur token={analogToken} />
let's have a `AlmostEqualTo` component like in web app and replace all usages by component to have consistency in spacing

2021-05-19 08:41 UTC, desfero commented on packages/wallet/app/modules/wallet-screen/module.ts
> +  // TODO ask Pawel why these are re exported?
i have no idea to be honest

2021-05-19 08:41 UTC, desfero commented on packages/wallet/storybook/index.tsx
> +        <SafeAreaView style={styles.storybookSafeAreaView} forceInset={{ top: "always" }}>
cool

2021-05-19 13:09 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +        <Text>
can't because many values aren't text like tx status, links etc

2021-05-19 13:10 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetailScreen.stories.tsx
> +  <NavigationContainer independent>
don't know where it came from, removed

2021-05-19 13:10 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/ViewCompanyProfile.tsx
> +const ViewCompanyProfile: React.FunctionComponent<{ etoId: string }> = ({ etoId }) => (
updated

2021-05-19 13:13 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/ViewOnEtherscan.tsx
> +const ViewOnEtherscan: React.FunctionComponent<{ txHash: string | TEthereumTxHash }> = ({
updated

2021-05-19 13:19 UTC, Schabaani commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetailScreen.stories.tsx
> +  <NavigationContainer independent>
independent comes from here: https://davidl.fr/blog/react-navigation-object-storybook

Since 2017, I follow the "Component Driven Development" way of working. Like Lego bricks, all my components are loosely-coupled and independent. I assemble them to test behavior with Storybook. But if you want to have access to the navigation you will encounter this error: {navigation} object is not defined.

2021-05-19 13:34 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/ViewCompanyProfile.tsx
> +        <Text style={styles.link}>
added rule

2021-05-19 13:35 UTC, arjunu commented on packages/wallet/app/components/shared/formatters/MoneySuite.stories.tsx
> +  <View>
it's specific to MoneySuite right now, we can do it if we decide to reuse it in future for some other story

2021-05-19 16:25 UTC, arjunu commented on packages/wallet/app/components/shared/links/ExternalLink.tsx
> +      {children ?? <Text>{trimAddress(url)}</Text>}
done

2021-05-19 16:27 UTC, arjunu commented on packages/wallet/app/modules/wallet-screen/module.ts
> +  // TODO ask Pawel why these are re exported?
ok removed

2021-05-19 16:35 UTC, arjunu commented on packages/wallet/app/components/shared/formatters/MoneySuite.tsx
> +          ≈ <Eur token={analogToken} />
done

2021-05-19 16:36 UTC, arjunu commented on packages/wallet/app/components/shared/CopyToClipboardButton.tsx
> +    accessibilityHint="Copy"
changed hint to "Click to copy"

2021-05-19 16:43 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetailsHeader.tsx
> +    maxWidth: 200,
actually yeah that;s better, changed to padding

2021-05-19 16:46 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +  date: string | number | Date | undefined;
fixed

2021-05-19 16:47 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetail.tsx
> +const TransactionDetail: React.FunctionComponent<TProps> = ({
yes but we don't know what designs will look like. We can do it later as it's a simple change

2021-05-19 16:50 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetailScreen.stories.tsx
> +  <NavigationContainer independent>
seems to work without it

2021-05-19 16:51 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetailsHeader.tsx
> +    ...typographyStyles.headline2,
removed

2021-05-19 16:56 UTC, arjunu commented on packages/wallet/app/components/shared/links/EtherscanAddressLink.tsx
> +    {children || <Text>{trimAddress(url)}</Text>}
updated

2021-05-20 09:47 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetail.tsx
> +  // Todo use TTranslatedString
updated

2021-05-20 10:06 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetail.tsx
> +    paddingLeft: 20,
updated

2021-05-20 10:22 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/TransactionDetail.tsx
> +    height: 56,
changed to min height, didn't give any padding

2021-05-20 10:44 UTC, arjunu commented on packages/wallet/app/components/screens/TransactionDetailScreen/transaction-detail-types/EtoTokensClaimTransactionDetails.tsx
> +  const claimed = createToken(
aha ok it works

2021-05-24 07:38 UTC, desfero commented on packages/wallet/app/components/screens/TransactionDetailScreen/BasicTransactionDetails.tsx
> +        <Text>
ah, i see

2021-05-24 07:47 UTC, desfero approved these changes

2021-05-25 09:09 UTC, KonradFilipiak approved these changes

2021-05-25 12:56 UTC, merged