Use generic modals for all simple modals
Neufund/platform-frontend pull request #4923
Opened 2021-05-03 16:31 UTC by arjunu

2021-05-05 10:48 UTC, arjunu commented on packages/web/app/components/dashboard/my-portfolio/PortfolioStats.tsx
> +          key={eto.etoId}
there are duplicate token names in io fixtures

2021-05-12 07:49 UTC, desfero requested changes

2021-05-12 07:49 UTC, desfero commented on packages/web/app/modules/generic-modal/actions.ts
> +    type: T;
let's extract type to a separate variable `TModalConfig` and also let's make a type system correct by removing optional from `componnetProps` and pass explicitly `undefined` where it's required

2021-05-12 07:49 UTC, desfero commented on packages/web/app/modules/generic-modal/reducer.ts
> +  type?: EGenericModalType;
i would say we should not use `optional` in-state but rather `| undefined` to explicitly set undefined values in `initialState` so it's easier to understand

2021-05-12 07:49 UTC, desfero commented on packages/web/app/modules/generic-modal/selectors.ts
> +export const selectGenericModal = (state: TAppGlobalState) => ({
let's use `reselect` here

2021-05-12 07:49 UTC, desfero commented on packages/web/app/components/modals/generic-modal/GenericModal.tsx
> +  let onClose: (() => void) | undefined = closeModal;
do we need onClose variable to just hold the reference to closeModal?

2021-05-17 11:15 UTC, arjunu commented on packages/web/app/components/modals/Modal.tsx
> +      className={cn(styles.modal, { [styles.fixed]: scrollable }, { [styles.noFrame]: noFrame })}
updated

2021-05-17 11:17 UTC, arjunu commented on packages/web/app/components/modals/generic-modal/GenericModal.tsx
> +  let onClose: (() => void) | undefined = closeModal;
removed

2021-05-17 11:22 UTC, arjunu commented on packages/web/app/components/modals/generic-modal/GenericModal.tsx
> +  return <Modal isOpen={false} />;
it's for close animation, if we return null then it is removed from DOM immediately

2021-05-17 11:23 UTC, arjunu commented on packages/web/app/components/modals/unverified-email-reminder/UnverifiedEmailReminderModal.tsx
> +      assertNever(
yes better, updated

2021-05-17 11:28 UTC, arjunu commented on packages/web/app/modules/generic-modal/selectors.ts
> +export const selectGenericModal = (state: TAppGlobalState) => ({
updated

2021-05-17 11:29 UTC, arjunu commented on packages/web/app/modules/generic-modal/reducer.ts
> +  type?: EGenericModalType;
updated

2021-05-17 11:31 UTC, arjunu commented on packages/web/app/modules/auth/email/sagas.ts
> +export function* checkTOSAgreement(): SagaGenerator<void> {
nice catch, moved

2021-05-17 11:33 UTC, arjunu commented on packages/web/app/components/modals/verify-bank-account-cta-modal/VerifyBankAccountCtaModal.tsx
> +// TODO use generic modal once it migrates to new design
https://github.com/Neufund/platform-frontend/issues/4960

2021-05-17 11:48 UTC, arjunu commented on packages/web/app/modules/generic-modal/actions.ts
> +    type: T;
done

2021-05-17 15:28 UTC, desfero commented on packages/web/app/components/modals/generic-modal/GenericModal.tsx
> +  return <Modal isOpen={false} />;
ahhh, i see

2021-05-17 15:29 UTC, desfero commented on packages/web/app/components/modals/verify-bank-account-cta-modal/VerifyBankAccountCtaModal.tsx
> +// TODO use generic modal once it migrates to new design
<3

2021-05-17 15:32 UTC, desfero approved these changes

2021-05-17 15:32 UTC, merged