#4911 [Mobile app] Returning user log in view design updates
Neufund/platform-frontend pull request #4924
Opened 2021-05-03 21:37 UTC by ozanmanav-ng

- UnlockAccountScreen edited with new layout.
- Deleted loading indicator from the common buttons and added "Loading..." text (double check this with @andywalton ?)
- Used full svg of the landingbackground1 and adjusted position for screen.

Tested on:
- Iphone 7
- Iphone 12
- Android Nexus S-L

2021-05-04 10:27 UTC, ozanmanav-ng commented
Updated description

2021-05-05 07:17 UTC, desfero requested changes

2021-05-05 07:17 UTC, desfero commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +        <Illustration type={EIllustrationType.LANDINGBACKGROUND1} />
So we don't use `Gyryscoping` animation here?

2021-05-05 07:17 UTC, desfero commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +          {authWallet?.name ? (
It's a little bit more tricky here than just displaying the name. 
Right now it only stores a fixture name (so only works in dev mode) but we need to change that code to put into the name also name from `KYC` data.
If you login as a `INV_HAS_EUR_HAS_KYC` fixture then you can find name in kyc `businessData` field.  

![image](https://user-images.githubusercontent.com/7031578/117107118-5a29b000-ad81-11eb-8eee-d65188c23757.png)

For user is an individual investor name should be under `individualData` key in kyc. We have a selector already available `selectClientName` that can be used as it should extract valid name from either `business` or `individual` data. 
What we can do is to sync name with wallet storage when we get `kyc` data from the backend after logging out. We should check if `authWallet.name` differs from `selectClientName` and if so change ` authWallet.name` to be the one from `selectClientName`.

2021-05-06 11:18 UTC, arjunu commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +            <View>
used fragment

2021-05-06 11:18 UTC, arjunu commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +            {intl.formatMessage({ id: "wallet.unlock-account-screen.log-in-face-id" })}
used FormattedMessage

2021-05-06 11:47 UTC, arjunu commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +            {intl.formatMessage({ id: "wallet.unlock-account-screen.log-in-face-id" })}
used biometricsType

2021-05-06 15:08 UTC, arjunu commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +              <HelperText style={styles.email}>{authWallet?.address}</HelperText>
replaced with email

2021-05-09 20:09 UTC, arjunu commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +          {authWallet?.name ? (
used `clientName ?? authWallet.name`

2021-05-09 20:53 UTC, arjunu commented on packages/wallet/app/components/modals/BiometricsPermissionModal/BiometricsPermissionModal.tsx
> +        approveText={<>Enable {BiometricsName[biometryType]}</>}
because now BiometricsName returns FormattedMessage, eventually we should replace the whole string with a new FormattedMessage that includes "Enable"

2021-05-09 20:56 UTC, arjunu commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +    paddingTop: 40,
in the design it is 40, can't use spacing styles here. It's a specific usage so I guess it's ok?

2021-05-12 13:08 UTC, desfero commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +    paddingTop: 40,
hm, imo we can use spacing that's close to the 40 px for consistency

2021-05-12 13:10 UTC, desfero commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +    clientName: kycApi.selectors.selectClientName(state),
Both auth and kyc are not yet available when you start the app from the beginning. We should save these values in `wallet` storage (or some other up to you) and just read values from the device storage

2021-05-12 13:49 UTC, desfero requested changes

2021-05-12 13:49 UTC, desfero commented on packages/wallet/app/components/screens/constants.tsx
> +import { TTranslatedString } from "types/*";
Let's remove that `*` and refactor how it was before :D

2021-05-12 13:49 UTC, desfero commented on packages/wallet/app/devUtils.ts
> +  "React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.",
ah, cool it was pretty annoying, let's monitor dependencies that are throwing that error and fix properly soon :D

2021-05-12 13:49 UTC, desfero commented on packages/wallet/patches/@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch
> +diff --git a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
let's create a Readme in patches and add some description (links to issues) why we are patching that

2021-05-17 12:04 UTC, arjunu commented on packages/wallet/patches/@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch
> +diff --git a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
added

2021-05-17 12:07 UTC, arjunu commented on packages/wallet/app/components/screens/constants.tsx
> +import { TTranslatedString } from "types/*";
done

2021-05-17 12:08 UTC, arjunu commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +    paddingTop: 40,
updated

2021-05-17 15:03 UTC, arjunu commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +  const name = authWallet?.clientName ?? authWallet?.name;
`clientName` wouldn't be available if kyc API failed and for backward compatibility

2021-05-17 15:03 UTC, arjunu commented on packages/wallet/app/components/screens/UnlockAccountScreen/UnlockAccountScreen.tsx
> +    clientName: kycApi.selectors.selectClientName(state),
done

2021-05-17 15:07 UTC, arjunu commented on packages/wallet/app/modules/auth/sagas.ts
> +function* saveMetadataToStorage(): SagaGenerator<void> {
couldn't find a better place to save, kyc has multiple actions and I didn't want to watch for them all.

2021-05-18 09:14 UTC, desfero requested changes

2021-05-18 12:04 UTC, arjunu commented on packages/wallet/app/modules/auth/module.ts
> +import { selectVerifiedUserEmail } from "@neufund/shared-modules/dist/modules/auth/user/selectors";
added

2021-05-18 12:05 UTC, arjunu commented on packages/wallet/app/modules/auth/sagas.ts
> +export function* saveMetadataToStorage(): SagaGenerator<void> {
moved

2021-05-19 09:12 UTC, desfero approved these changes

2021-05-20 08:02 UTC, merged