#4913 Align tab bar icons with design
Neufund/platform-frontend pull request #4961
Opened 2021-05-17 11:36 UTC by ozanmanav-ng

2021-05-17 16:04 UTC, desfero requested changes

2021-05-17 16:04 UTC, desfero commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
>          inactiveTintColor: navigationTheme.colors.text,
inactive tint color should be a base gray one. We should also specify active tint color to base gray (by default it's base gray but we never know when react-navigation updates styling)

2021-05-17 16:04 UTC, desfero commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
> +          paddingBottom: insets.bottom + TAB_PADDING,
what that change is fixing exactly? I'm trying to spot the difference but it seems the same

2021-05-17 16:04 UTC, desfero commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
> +              <MenuLabel style={[styles.label, { color }]}>{name}</MenuLabel>
Let's use `MenuLabelBold`

2021-05-17 16:04 UTC, desfero commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
> +    letterSpacing: 0.1,
btw do we need that later spacing? Why we don't use the one that was set by default in typography? If there is some issue with dithering we can try to reduce `letterSpacing to 0.1` but that should be also done on a typography level.

Also we don't need `fontWeight` probably if we use `menuLabelBold`

2021-05-17 16:57 UTC, ozanmanav-ng commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
>          inactiveTintColor: navigationTheme.colors.text,
Active tint color looks the same, according to Design. 

![image](https://user-images.githubusercontent.com/82657734/118527654-2ae44d00-b74a-11eb-83b1-3884184f98c1.png)

https://app.zeplin.io/project/5e6f48a43076c61012fd3793/screen/606c646c2493089832b1e969

2021-05-17 16:59 UTC, ozanmanav-ng commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
> +          paddingBottom: insets.bottom + TAB_PADDING,
You should check with iphone 11 and iphone 7. I used it to bring the text and icon closer together.

2021-05-17 16:59 UTC, ozanmanav-ng commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
> +              <MenuLabel style={[styles.label, { color }]}>{name}</MenuLabel>
done

2021-05-17 17:25 UTC, ozanmanav-ng commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
> +          height: tabHeight,
When I talked to Andrew,  he asked me to use 56px on non-insets devices. That's why we have to use the height. I have refactored as follows. I used the padding to bring the icon and text closer together.
 
![image](https://user-images.githubusercontent.com/82657734/118530941-ebb7fb00-b74d-11eb-9765-3d81325598ae.png)

2021-05-17 20:05 UTC, ozanmanav-ng commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
> +          paddingBottom: insets.bottom + TAB_PADDING,
I refactored to this:
![image](https://user-images.githubusercontent.com/82657734/118549579-58d68b00-b764-11eb-8fd0-bb9a160a8ffe.png)

2021-05-18 10:48 UTC, ozanmanav-ng commented on packages/wallet/app/router/AppAuthRouterTabs.tsx
>          inactiveTintColor: navigationTheme.colors.text,
done

2021-05-18 16:22 UTC, desfero approved these changes

2021-05-20 13:49 UTC, KonradFilipiak approved these changes

2021-05-20 13:49 UTC, merged