Amish/4136 i18n
Neufund/platform-frontend pull request #4978
Opened 2021-05-24 04:47 UTC by Schabaani

2021-06-10 12:09 UTC, desfero commented
Closing for now

2021-06-21 07:54 UTC, desfero requested changes
Small changes

2021-06-21 07:54 UTC, desfero commented on packages/wallet/package.json
> +    "formatjs extract": "prettier --check '**/*.{ts,tsx,js,json,md,gql}'",
some copy paste?

2021-06-21 07:54 UTC, desfero commented on packages/wallet/package.json
> +    "intl:extract:formatjs": "formatjs extract 'app/**/*.tsx' --out-file app/intl/tmp/en-en.json",
ok, i'm wondering if we can move whole process to a custom made script?
We can use Node API https://formatjs.io/docs/tooling/cli#node-api to call extract messages.

Also would be good to set https://formatjs.io/docs/tooling/cli#--throws flag to get an error if something goes wrong

2021-06-21 07:54 UTC, desfero commented on packages/wallet/scripts/merge-messages-with-locales.js
> +    const fileContents = readFileSync(path, "utf8") || def;
i'm wondering why do we need `|| def` given it should throw when file doesn't exist and then we push default value?

2021-06-21 07:54 UTC, desfero commented on packages/wallet/app/intl/README.md
> +# Intl
🎖️

2021-06-21 07:54 UTC, desfero commented on packages/wallet/app/intl/en-en.json
> +  "screen.account-backup.write-down-phrase-warning": "If you lose access to your device, the only way to restore your funds and account is with your recovery phrase or private key.\n\nPlease write do
Can you make sure `\n\n` works properly?

2021-06-21 11:17 UTC, arjunu commented on packages/wallet/app/intl/en-en.json
> +  "screen.account-backup.write-down-phrase-warning": "If you lose access to your device, the only way to restore your funds and account is with your recovery phrase or private key.\n\nPlease write do
works

2021-06-21 11:17 UTC, arjunu commented on packages/wallet/package.json
> +    "formatjs extract": "prettier --check '**/*.{ts,tsx,js,json,md,gql}'",
oops removed

2021-06-21 11:38 UTC, arjunu commented on packages/wallet/scripts/merge-messages-with-locales.js
> +    const fileContents = readFileSync(path, "utf8") || def;
good point, removed

2021-06-21 12:04 UTC, arjunu commented on packages/wallet/package.json
> +    "intl:extract:formatjs": "formatjs extract 'app/**/*.tsx' --out-file app/intl/tmp/en-en.json",
updated

2021-06-22 13:21 UTC, desfero commented on packages/wallet/app/intl/en-en.json
> +  "screen.account-backup.write-down-phrase-warning": "If you lose access to your device, the only way to restore your funds and account is with your recovery phrase or private key.\n\nPlease write do
cool

2021-06-22 13:22 UTC, desfero approved these changes

2021-06-22 13:23 UTC, merged