Ozan/4931 styling changes for the light wallet
Neufund/platform-frontend pull request #4992
Opened 2021-06-04 14:32 UTC by ozanmanav-ng

We tried apply responsive %95 not fully, but we can check the acceptability together.

Here some screenshots from the development:
4K 2560px
![image](https://user-images.githubusercontent.com/82657734/120817658-8f7d1580-c55a-11eb-9047-5007b77031a5.png)

Laptop L 1440px
![image](https://user-images.githubusercontent.com/82657734/120817702-9b68d780-c55a-11eb-9169-e0484ffe285d.png)

Laptop 1024px
![image](https://user-images.githubusercontent.com/82657734/120817774-a885c680-c55a-11eb-83e4-e72a00a06cde.png)

Tablet 768px
![image](https://user-images.githubusercontent.com/82657734/120817823-b3405b80-c55a-11eb-99b9-76dc45460b8b.png)

Mobile <768px
![image](https://user-images.githubusercontent.com/82657734/120817892-c3f0d180-c55a-11eb-8186-01c7d9504262.png)

2021-06-09 11:50 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.tsx
> +              <li className={styles.qrCodeContainerMobile}>
what is this? some left over?

2021-06-09 11:58 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.tsx
> +              <li className={styles.qrCodeContainerMobile}>
also it has a border in mobile screens
![image](https://user-images.githubusercontent.com/4038217/121350322-cff9dc00-c92a-11eb-905a-8cdcc26f380f.png)

2021-06-09 12:00 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.tsx
> +              <li className={styles.qrCodeContainerMobile}>
and you can use a variable 
```
const qrCodeLayout = <LightWalletExportLayoutQrCode salt={salt} email={email} intl={intl} />;

// ...

<li className={styles.qrCodeContainerMobile}>{qrCodeLayout}</li>

<div className={styles.qrCodeContainer}>{qrCodeLayout}</li>
```

2021-06-09 12:02 UTC, arjunu requested changes
space between "Please follow..." and step 1 is more in the design

![image](https://user-images.githubusercontent.com/4038217/121350704-426abc00-c92b-11eb-9625-da459a9c1948.png)

2021-06-09 12:07 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.module.scss
> +  margin-top: 50px;
can you use `px-to-rem` for all widths, heights, paddings and margins

2021-06-09 12:09 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.module.scss
> +  @media screen and (min-width: 769px) {
is it possible to use `media-breakpoint-up(xl)`, `media-breakpoint-up(sm)` etc instead? We have used it in other places in the app

2021-06-09 12:09 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.module.scss
> +  margin-top: 50px;
margin-top: `px-to-tem(50px);`

2021-06-09 12:13 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayoutQRCode.tsx
> +const LightWalletExportLayoutQrCode: FC<TExternalProps> = ({ salt, email, intl }) => (
this component is unecessary,
you can put this in a variable in LightWalletExportLayoutInternal

```
const lightWalletExportLayoutQrCode = <QRCodeImage
    alt={intl.formatIntlMessage("light-wallet-export.qr-code-alt")}
    uri={generateLightWalletImportUri(salt, email)}
    data-test-id="light-wallet-export.qr-code"
    className={styles.qrCode}
  />;
  ```
  and use this variable

2021-06-09 12:15 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.tsx
> +                      <div className={styles.link}>
use span tag

2021-06-09 12:15 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.tsx
> +                      <div className={styles.link}>
use span tag

2021-06-09 12:17 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.tsx
> +                title={`${intl.formatIntlMessage("light-wallet-export.step")} 2`}
the number should be part of the intl message in case we need to translate the number too

2021-06-09 12:18 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.tsx
> +            <p className={cn(styles.descriptionText, "my-3")}>
we are trying to move away from bootstrap, so can u replace this with custom css

2021-06-09 12:20 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayoutStepListItem.tsx
> +import * as styles from "./LightWalletExportLayout.module.scss";
use `LightWalletExportLayoutStepListItem.module.scss`

2021-06-09 12:24 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.module.scss
> +    display: flex;
you can use also use display grid for `steps` and give grid gap so there's no unnecessary margin bottom for last item

2021-06-09 12:29 UTC, arjunu commented on packages/web/app/assets/img/light-wallet/step_icon_1.svg
> +<svg width="56" height="56" viewBox="0 0 56 56" fill="none" xmlns="http://www.w3.org/2000/svg">
looks like these step icon svgs aren't minified, you can ask Kacper to export compressed images or use https://jakearchibald.github.io/svgomg/

2021-06-09 12:30 UTC, arjunu commented on packages/web/app/components/light-wallet-export/LightWalletExportLayoutStepListItem.tsx
> +const LightWalletExportLayoutStepListItem: FC<TExternalProps> = ({ title, children, icon }) => (
```suggestion
const LightWalletExportLayoutStepListItem: React.FunctionComponent<TExternalProps> = ({ title, children, icon }) => (
```

for consistency with rest of the code

2021-06-09 18:45 UTC, ozanmanav-ng commented
> space between "Please follow..." and step 1 is more in the design
> 
> ![image](https://user-images.githubusercontent.com/4038217/121350704-426abc00-c92b-11eb-9625-da459a9c1948.png)

2021-06-09 19:15 UTC, ozanmanav-ng commented on packages/web/app/assets/img/light-wallet/step_icon_1.svg
> +<svg width="56" height="56" viewBox="0 0 56 56" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2021-06-09 19:16 UTC, ozanmanav-ng commented on packages/web/app/components/light-wallet-export/LightWalletExportLayout.module.scss
> +  @media screen and (min-width: 769px) {
I couldn't defines of the these ones, can you give me file name?

2021-06-13 21:07 UTC, arjunu approved these changes

2021-06-14 10:11 UTC, merged