Ledger use web USB
Neufund/platform-frontend pull request #4997
Opened 2021-06-07 16:28 UTC by arjunu

2021-06-07 16:29 UTC, arjunu commented on packages/web/app/lib/web3/ledger-wallet/LedgerConnector.ts
> +      accounts.push(await this.getMultipleAccountsFromHdPath(derivationPaths[i], 0, 1));
it can only perform one operation at a time so we should do it in serial

2021-06-08 16:15 UTC, ozanmanav-ng approved these changes
LGTM

2021-06-11 08:55 UTC, desfero requested changes

2021-06-11 08:55 UTC, desfero commented on packages/web/app/lib/web3/ledger-wallet/LedgerConnector.ts
> +      accounts.push(await this.getMultipleAccountsFromHdPath(derivationPaths[i], 0, 1));
let's put a comment about that so we know the reason

2021-06-17 08:35 UTC, arjunu commented on packages/web/app/lib/web3/ledger-wallet/LedgerConnector.ts
> +      accounts.push(await this.getMultipleAccountsFromHdPath(derivationPaths[i], 0, 1));
added

2021-06-18 09:33 UTC, desfero approved these changes

2021-06-19 19:49 UTC, merged