Implement getRequiredEnv & validateEnv for Wallet
Neufund/platform-frontend pull request #5004
Opened 2021-06-14 11:36 UTC by ozanmanav-ng

2021-06-14 14:39 UTC, arjunu commented on packages/wallet/.env.template
> +NF_BIOMETRICS_OVERRIDE=
this flag is no longer used, you can remove it from all places

2021-06-16 11:51 UTC, arjunu commented on packages/wallet/scripts/validate-env-wallet.js
> +validateEnvWallet();
```suggestion
const platform = process.argv[2]
validateEnvWallet(platform);
```

because this way it is clear that `platform` is coming from outside

2021-06-16 11:52 UTC, arjunu commented on packages/wallet/package.json
> +    "validate-env-wallet:ios": "node scripts/validate-env-wallet.js ios",
just `validate-env` should we enough, we know it's wallet

2021-06-22 09:30 UTC, arjunu commented on packages/wallet/scripts/validate-env.js
> +function validateEnv() {
```suggestion
function validateEnv(platform) {
```

2021-06-22 09:30 UTC, arjunu commented on packages/wallet/scripts/validate-env.js
> +validateEnv(platform);
```suggestion
validateEnv(process.argv[2]);
```

2021-06-22 11:13 UTC, ozanmanav-ng commented on packages/wallet/scripts/validate-env.js
> +function validateEnv() {
done

2021-06-22 11:13 UTC, ozanmanav-ng commented on packages/wallet/scripts/validate-env.js
> +validateEnv(platform);
done

2021-06-22 13:22 UTC, arjunu approved these changes

2021-06-22 13:31 UTC, desfero requested changes
Some small changes

2021-06-22 13:31 UTC, desfero commented on packages/wallet/appcenter-pre-build.sh
> +  echo "Validating Env Variables ..."
some spacing before `echo`

2021-06-22 13:31 UTC, desfero commented on packages/wallet/scripts/validate-env.js
> +  if (!platform) {
I would move that check to the top of the function as then we can declare and define both `evns` `templateEnvs` together to avoid mutation

2021-06-22 13:31 UTC, desfero commented on packages/wallet/scripts/validate-env.js
> +    e => !e.startsWith(platform === "ios" ? "NF_ANDROID" : "NF_IOS"),
`platform === "ios" ? "NF_ANDROID" : "NF_IOS"`
we can keep that as a separate variable to not duplicate on line 33 and 35

2021-06-23 10:04 UTC, arjunu commented on packages/wallet/scripts/validate-env.js
> +  envs = envs.filter(e => !e.startsWith(excludeEnvPrefix));
I think what Pawel meant was

```suggestion
  const excludeEnvPrefix = platform === "ios" ? "NF_ANDROID" : "NF_IOS";
  const envs = Object.keys(readEnv(ENV_PATH)).filter(e => !e.startsWith(excludeEnvPrefix));;
  const templateEnvs = Object.keys(readEnv(ENV_TEMPLATE_PATH)).filter(e => !e.startsWith(excludeEnvPrefix));
```

2021-06-23 10:07 UTC, ozanmanav-ng commented on packages/wallet/scripts/validate-env.js
> +  envs = envs.filter(e => !e.startsWith(excludeEnvPrefix));
done

2021-06-23 10:07 UTC, arjunu commented on packages/wallet/scripts/validate-env.js
> +  if (!platform) {
```suggestion
  if (!platform || (platform!=="android" && platform!=="ios")) {
```

2021-06-23 10:33 UTC, ozanmanav-ng commented on packages/wallet/scripts/validate-env.js
> +  if (!platform) {
done

2021-06-23 12:28 UTC, arjunu approved these changes

2021-06-23 12:29 UTC, merged